(self.AMP=self.AMP||[]).push({n:"amp-consent",v:"2009252320001",f:(function(AMP,_){
'use strict';var h,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var l;
if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var ca={a:!0},da={};try{da.__proto__=ca;m=da.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ea=l,fa={TCF_V1:1,TCF_V2:2,US_PRIVACY_STRING:3};function p(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ha(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ia=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ja=Object.prototype.toString;function q(a){return"[object Object]"===ja.call(a)}function ka(a){return"number"===typeof a&&isFinite(a)}function r(a,b){for(var c in a)if(a[c]===b)return!0;return!1};var t=self.AMP_CONFIG||{},la=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ma(a){if(!self.document||!self.document.head||self.location&&la.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var na={thirdParty:t.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:t.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof t.thirdPartyFrameRegex?new RegExp(t.thirdPartyFrameRegex):t.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:t.cdnUrl||ma("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:la,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:t.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:t.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:t.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:t.geoApiUrl||ma("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var u=self.__AMP_LOG;function v(a){u.user||(u.user=oa());var b=u.user.win;return a&&a.ownerDocument.defaultView!=b?u.userForEmbed?u.userForEmbed:u.userForEmbed=oa():u.user}function oa(){throw Error("failed to call initLogConstructor");}function x(){if(u.dev)return u.dev;throw Error("failed to call initLogConstructor");}function y(a,b,c,d,e){return v().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var z;function pa(a){try{var b=a.ownerDocument,c=b.createElement("div"),d=b.createElement("div");c.appendChild(d);return c.querySelector(":scope div")===d}catch(e){return!1}};var A=Object.prototype.hasOwnProperty;function B(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function C(a){return a||{}}
function qa(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(b={};0<d.length;){var e=d.shift();b.I=e.t;b.H=e.s;b.da=e.d;if(c.includes(b.H))throw Error("Source object has a circular reference.");c.push(b.H);b.I!==b.H&&(1<b.da?Object.assign(b.I,b.H):Object.keys(b.H).forEach(function(a){return function(b){var c=a.H[b];if(A.call(a.I,b)){var e=a.I[b];if(q(c)&&q(e)){d.push({t:e,s:c,d:a.da+1});return}}a.I[b]=c}}(b)));b={H:b.H,I:b.I,da:b.da}}return a};function D(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function ra(a,b){a.insertBefore(b,a.firstChild)}function sa(a){/^[\w-]+$/.test("placeholder");return a.querySelector("placeholder")}function ta(a,b){a.classList.add("i-amphtml-scoped");var c=b.replace(/^|,/g,"$&.i-amphtml-scoped "),d=a.querySelectorAll(c);a.classList.remove("i-amphtml-scoped");return d}function ua(a){a=a.tagName;return D(a,"AMP-")&&!("AMP-STICKY-AD-TOP-PADDING"==a||"AMP-BODY"==a)}
function va(a){ua(a);if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new p;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function wa(a,b){if(!isFinite(5))throw Error("Invalid depth: 5");if(a===b)return!0;for(a=[{a:a,b:b,depth:5}];0<a.length;){var c=a.shift();b=c.a;var d=c.b;c=c.depth;if(0<c){if(typeof b!==typeof d)return!1;if(Array.isArray(b)&&Array.isArray(d)){if(b.length!==d.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:d[e],depth:c-1});continue}else if(b&&d&&"object"===typeof b&&"object"===typeof d){var f=Object.keys(b),g=Object.keys(d);if(f.length!==g.length)return!1;for(e=0;e<f.length;e++){var k=
f[e];a.push({a:b[k],b:d[k],depth:c-1})}continue}}if(b!==d)return!1}return!0};var xa={ACCEPTED:1,REJECTED:2,DISMISSED:3,NOT_REQUIRED:4,UNKNOWN:5};function E(a){return a?A.call(a,"isDirty")&&1==a.isDirty?!0:!1:!1}function ya(a){return 1==a?!0:2==a?!1:null}function za(a,b,c){if(!a&&!b)return!0;if(a&&b){var d=ya(a.consentState)===ya(b.consentState),e=(a.consentString||"")===(b.consentString||"");var f=c?!!a.isDirty===!!c:!!a.isDirty===!!b.isDirty;var g=wa(a.consentMetadata,b.consentMetadata);return d&&e&&g&&f}return!1}
function F(a,b,c,d){return{consentState:a,consentString:b,consentMetadata:c,isDirty:d}}function Aa(a,b,c){return{consentStringType:a,additionalConsent:b,gdprApplies:c}}function Ba(a){return!0===a||1===a?1:!1===a||0===a?2:5}function Ca(a){return a.consentString?!0:1===a.consentState||2===a.consentState}function G(a){return 1===a?"accepted":2===a?"rejected":"unknown"};var Da;function H(){return Da?Da:Da=Promise.resolve(void 0)};var Ea={appconsent:{consentInstanceId:"appconsent",checkConsentHref:"https://collector.appconsent.io/amp/check-consent",promptUISrc:"https://cdn.appconsent.io/loader.html"},ConsentManager:{consentInstanceId:"ConsentManager",checkConsentHref:"https://consentmanager.mgr.consensu.org/delivery/ampcheck.php",promptUISrc:"https://consentmanager.mgr.consensu.org/delivery/ampui.php"},didomi:{consentInstanceId:"didomi",checkConsentHref:"https://api.privacy-center.org/amp/check-consent",promptUISrc:"https://sdk-amp.privacy-center.org/loader.html"},
iubenda:{consentInstanceId:"iubenda",checkConsentHref:"https://amp.iubenda.com/cs/amp/checkConsent",promptUISrc:"https://www.iubenda.com/en/help/22135-cookie-solution-amp"},sirdata:{consentInstanceId:"sirdata",checkConsentHref:"https://sddan.mgr.consensu.org/api/v1/public/amp/check",promptUISrc:"https://ui.sddan.mgr.consensu.org/amp.html"},Marfeel:{consentInstanceId:"Marfeel",checkConsentHref:"https://live.mrf.io/cmp/consents/amp",promptUISrc:"https://marfeel.mgr.consensu.org/amp/index.html"},Ogury:{consentInstanceId:"Ogury",
checkConsentHref:"https://api.ogury.mgr.consensu.org/v1/check-for-consent",promptUISrc:"https://www.ogury.mgr.consensu.org/amp.html"},onetrust:{consentInstanceId:"onetrust",checkConsentHref:"https://cdn.cookielaw.org/amp/consent/check",promptUISrc:" https://amp.onetrust.mgr.consensu.org/"},opencmp:{consentInstanceId:"opencmp",checkConsentHref:"https://amp.opencmp.net/consent/check",promptUISrc:"https://cdn.opencmp.net/tcf-v2/amp/cmp.html"},SourcePoint:{consentInstanceId:"SourcePoint",checkConsentHref:"https://sourcepoint.mgr.consensu.org/consent/v2/amp",
promptUISrc:"https://amp.pm.sourcepoint.mgr.consensu.org/"},Usercentrics:{consentInstanceId:"Usercentrics",checkConsentHref:"https://consents.usercentrics.eu/amp/checkConsent",promptUISrc:"https://amp.usercentrics.eu/amp.html"}};function I(){this.$a=100;this.ta=this.Ia=0;this.ea=Object.create(null)}I.prototype.has=function(a){return!!this.ea[a]};I.prototype.get=function(a){var b=this.ea[a];if(b)return b.access=++this.ta,b.payload};I.prototype.put=function(a,b){this.has(a)||this.Ia++;this.ea[a]={payload:b,access:this.ta};if(!(this.Ia<=this.$a)){x().warn("lru-cache","Trimming LRU cache");a=this.ea;var c=this.ta+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.Ia--)}};var Fa=C({c:!0,v:!0,a:!0,ad:!0}),Ga,Ha,Ia=/[?&]amp_js[^&]*/,Ja=/[?&]amp_gsa[^&]*/,Ka=/[?&]amp_r[^&]*/,La=/[?&]amp_kit[^&]*/,Ma=/[?&]usqp[^&]*/;
function J(a){Ga||(Ga=self.document.createElement("a"),Ha=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new I));var b=Ha,c=Ga;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function Na(a,b){var c=void 0===c?"source":c;y(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=J(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);y(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}
function Oa(a){"string"==typeof a&&(a=J(a));var b=a;"string"==typeof b&&(b=J(b));if(!na.cdnProxyRegex.test(b.origin))return a.href;b=a.pathname.split("/");y(Fa[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);y(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Ia,"").replace(Ja,"").replace(Ka,"").replace(La,"").replace(Ma,"").replace(/^[?&]/,
""))?"?"+d:"":"";return b+d+(a.hash||"")}function Pa(a,b){"string"==typeof b&&(b=J(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=J(d));c=c.replace(/\\/g,"/");var e=J(c);c=D(c.toLowerCase(),e.protocol)?e.href:D(c,"//")?d.protocol+c:D(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c};function Qa(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){x().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function Ra(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;if(d.__AMP__EXPERIMENT_TOGGLES)var f=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);f=d.__AMP__EXPERIMENT_TOGGLES;if(d.AMP_CONFIG)for(var g in d.AMP_CONFIG){var k=d.AMP_CONFIG[g];"number"===typeof k&&0<=k&&1>=k&&(f[g]=Math.random()<k)}if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(g=d.AMP_CONFIG["allow-doc-opt-in"],
k=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){k=k.getAttribute("content").split(",");for(var n=0;n<k.length;n++)-1!=g.indexOf(k[n])&&(f[k[n]]=!0)}Object.assign(f,Qa(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&0<d.AMP_CONFIG["allow-url-opt-in"].length){g=d.AMP_CONFIG["allow-url-opt-in"];k=d.location.originalHash||d.location.hash;d=Object.create(null);if(k)for(var w;w=ia.exec(k);)n=ha(w[1],w[1]),w=w[2]?ha(w[2].replace(/\+/g," "),w[2]):"",d[n]=w;for(k=
0;k<g.length;k++)n=d["e-"+g[k]],"1"==n&&(f[g[k]]=!0),"0"==n&&(f[g[k]]=!1)}}var qb=!!f["ampdoc-fie"];e&&!qb?b=Sa(c,b)?K(c,b):null:(a=L(a),a=M(a),b=Sa(a,b)?K(a,b):null);return b}function N(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return K(a,b)}function O(a,b){var c=L(a);c=M(c);return K(c,b)}function P(a,b){a=M(a);var c=Ta(a,b);c?b=c:(a=Ua(a),a[b]=Va(),b=a[b].promise);return b}function L(a){return a.nodeType?N((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function M(a){a=L(a);return a.isSingleDoc()?a.win:a}function K(a,b){Sa(a,b);a=Ua(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ta(a,b){var c=Ua(a)[b];if(c){if(c.promise)return c.promise;K(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ua(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Sa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Va(){var a=new p,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Wa(a){var b=Ta(M(a),"geo");if(b)return b;var c=L(a);return c.waitForBodyOpen().then(function(){var a=c.win;var b=c.win.document.head;if(b){var f={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var g=0;g<b.length;g++){var k=b[g];k=k.getAttribute("custom-element")||k.getAttribute("custom-template");f[k]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-geo")?N(a,"extensions").waitForExtension(a,"amp-geo"):H()}).then(function(){return Ta(M(a),"geo")})};var Xa={promptUI:!0,checkConsentHref:!0,promptIfUnknownForGeoGroup:!0,onUpdateHref:!0},Ya={CLIENT_ID:!0,PAGE_VIEW_ID:!0,PAGE_VIEW_ID_64:!0};function Za(a){this.V=a;this.va=this.Z=null}Za.prototype.getConsentConfigPromise=function(){this.va||(this.va=$a(this));return this.va};Za.prototype.getMatchedGeoGroup=function(){return this.Z};
function ab(a){if(!a.consents)return a;var b=Object.keys(a.consents);y(1>=b.length,"%s: only single consent instance is supported","amp-consent/consent-config");if(0<b.length){a.consentInstanceId=b[0];var c=a.consents[b[0]],d=Object.keys(c);for(b=0;b<d.length;b++){var e=d[b];!a[e]&&Xa[e]&&(a[d[b]]=c[d[b]])}}delete a.consents;return a}
function $a(a){var b=ab(y(bb(a),"%s: Inline config not found")),c=cb(a),d=qa(c||{},b||{});y(d.consentInstanceId,"%s: consentInstanceId to store consent info is required","amp-consent/consent-config");if(d.policy)for(var e=Object.keys(d.policy),f=0;f<e.length;f++)"default"!=e[f]&&(v().warn("amp-consent/consent-config","policy %s is currently not supported and will be ignored",e[f]),delete d.policy[e[f]]);var g=d.promptIfUnknownForGeoGroup;"string"===typeof g?(d.consentRequired=!1,e={},d.geoOverride=
(e[g]={consentRequired:!0},e)):void 0===d.consentRequired&&d.checkConsentHref&&(d.consentRequired="remote");return db(a,d).then(function(a){var b=a.consentRequired;y("boolean"===typeof b||"remote"===b,"`consentRequired` is required","amp-consent/consent-config");"remote"===b&&y(a.checkConsentHref,"%s: `checkConsentHref` must be specified if `consentRequired` is remote","amp-consent/consent-config");return a}).then(function(b){var c=a.V;/^[\w-]+$/.test("amp-story-consent");(void 0!==z?z:z=pa(c))?c=
c.querySelector("> amp-story-consent".replace(/^|,/g,"$&:scope ")):(c=ta(c,"> amp-story-consent"),c=void 0===c[0]?null:c[0]);c&&y(!b.promptUISrc,"%s: `promptUiSrc` cannot be specified while using %s.","amp-consent/consent-config","amp-story-consent");return b})}
function db(a,b){return b.geoOverride?Wa(a.V).then(function(c){y(c,"%s: requires <amp-geo> to use `geoOverride`","amp-consent/consent-config");for(var d=B(b),e=Object.keys(b.geoOverride),f=0;f<e.length;f++)if(2===c.isInCountryGroup(e[f])){var g=b.geoOverride[e[f]];A.call(g,"consentInstanceId")&&(v().error("amp-consent/consent-config","consentInstanceId cannot be overriden in geoGroup:",e[f]),delete g.consentInstanceId);qa(d,g);a.Z=e[f];break}delete d.geoOverride;return d}):Promise.resolve(b)}
function bb(a){try{var b=a.V;/^[\w-]+$/.test("script");var c=(void 0!==z?z:z=pa(b))?b.querySelectorAll("> script".replace(/^|,/g,"$&:scope ")):ta(b,"> script");if(1!==c.length)throw Error("Found "+c.length+" <script> children. Expected 1.");var d=c[0];if("SCRIPT"!=d.tagName||!d.hasAttribute("type")||"APPLICATION/JSON"!=d.getAttribute("type").toUpperCase())throw Error('<script> child must have type="application/json"');try{var e=JSON.parse(d.textContent)}catch(f){throw Error("Failed to parse <script> contents. Is it valid JSON?");
}return e}catch(f){throw v(a.V).createError("amp-consent/consent-config",f);}}function cb(a){a=a.V.getAttribute("type");if(!a)return null;y(Ea[a],"%s: invalid CMP type %s","amp-consent/consent-config",a);var b=Ea[a];a=["consentInstanceId","checkConsentHref","promptUISrc"];for(var c=0;c<a.length;c++);return b}function eb(a,b){return Ra(a,"url-replace").expandUrlAsync(b,{CLIENT_ID:fb(a)},Ya)}
function fb(a){return P(a,"cid").then(function(a){return a.get({scope:"AMP-CONSENT",createCookieIfNotPresent:!0},H())})}function gb(a,b){var c={};c[b]=void 0;var d={waitFor:c},e=[4,1,2,3],f={waitFor:c,timeout:{seconds:0,fallbackAction:"reject"},unblockOn:e};a._till_responded={waitFor:c,unblockOn:e};a._till_accepted=d;a._auto_reject=f;if(a&&a["default"])return a;a["default"]=d;return a};function hb(){this.B=null}h=hb.prototype;h.add=function(a){var b=this;this.B||(this.B=[]);this.B.push(a);return function(){b.remove(a)}};h.remove=function(a){this.B&&(a=this.B.indexOf(a),-1<a&&this.B.splice(a,1))};h.removeAll=function(){this.B&&(this.B.length=0)};h.fire=function(a){if(this.B)for(var b=this.B,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.B?this.B.length:0};var ib={"default":!0,_till_responded:!0,_till_accepted:!0,_auto_reject:!0};function jb(a){this.o=a;this.N=B();this.K=B();this.La=P(this.o,"consentStateManager");this.Pa=new p;var b=new p;this.cb=b.promise;this.za=b.resolve;this.Qa=new hb;this.fa=this.ja=this.F=this.Oa=null}h=jb.prototype;h.setLegacyConsentInstanceId=function(a){this.Oa=a;this.W()};
h.registerConsentPolicyInstance=function(a,b){var c=this;if(!this.K[a]){var d=Object.keys(b.waitFor||{});if(1!==d.length||d[0]!==this.Oa)v().error("consent-policy-manager","invalid waitFor value, consent policy will never resolve");else{var e=new kb(b);this.K[a]=e;this.N[a]&&(this.N[a].resolve(),this.N[a]=null);this.cb.then(function(){c.F&&e.evaluate(c.F);c.Qa.add(function(a){e.evaluate(a)});c.Pa.promise.then(function(){e.startTimeout(c.o.win)})})}}};
h.W=function(){var a=this;this.La.then(function(b){b.whenConsentReady().then(function(){b.onConsentStateChange(function(b){var c=b.consentState,e=b.consentMetadata,f=a.ja,g=a.fa;a.ja=b.consentString;a.fa=e;5!==c&&(4==c?1!=a.F&&2!=a.F&&(a.F=4):3==c?(null===a.F&&(a.F=5),a.ja=f,a.fa=g):a.F=c,a.Qa.fire(a.F));a.za&&(a.za(),a.za=null)})})})};h.enableTimeout=function(){this.Pa.resolve()};
h.whenPolicyResolved=function(a){var b=this;return ib[a]?lb(this,a).then(function(){return b.K[a].getReadyPromise().then(function(){return b.K[a].getCurrentPolicyStatus()})}):(v().error("consent-policy-manager","can not find policy %s, only predefined policies are supported",a),Promise.resolve(4))};
h.whenPolicyUnblock=function(a){var b=this;return ib[a]?lb(this,a).then(function(){return b.K[a].getReadyPromise().then(function(){return b.K[a].shouldUnblock()})}):(v().error("consent-policy-manager","can not find policy %s, only predefined policies are supported",a),Promise.resolve(!1))};h.getMergedSharedData=function(a){var b=this;return this.whenPolicyResolved(a).then(function(){return b.La}).then(function(a){return a.getConsentInstanceSharedData()})};
h.getConsentStringInfo=function(a){var b=this;return this.whenPolicyResolved(a).then(function(){return b.ja})};h.getConsentMetadataInfo=function(a){var b=this;return this.whenPolicyResolved(a).then(function(){return b.fa})};function lb(a,b){if(a.K[b])return H();a.N[b]||(a.N[b]=new p);return a.N[b].promise}function kb(a){this.ab=a;var b=new p;this.gb=b.promise;this.qa=b.resolve;this.Ja=4;this.ib=a.unblockOn||[1,3]}h=kb.prototype;
h.startTimeout=function(a){var b=this,c=this.ab.timeout,d=null,e;void 0!=c&&(q(c)?(c.fallbackAction&&"reject"==c.fallbackAction?e=2:c.fallbackAction&&"dismiss"!=c.fallbackAction&&v().error("consent-policy-manager","unsupported fallbackAction %s",c.fallbackAction),d=c.seconds):d=c,y(ka(d),"invalid timeout value %s",d));null!=d&&a.setTimeout(function(){e=e||5;b.evaluate(e,!0)},1E3*d)};
h.evaluate=function(a,b){b=void 0===b?!1:b;!a||b&&!this.qa||(this.Ja=1===a?1:2===a?2:4===a?3:4,this.qa&&(this.qa(),this.qa=null))};h.getReadyPromise=function(){return this.gb};h.getCurrentPolicyStatus=function(){return this.Ja};h.shouldUnblock=function(){return-1<this.ib.indexOf(this.Ja)};function mb(a){this.o=a;this.ia=this.xa=this.wa=this.D=this.Sa=null}h=mb.prototype;h.registerConsentInstance=function(a,b){this.D?x().error("CONSENT-STATE-MANAGER","Cannot register consent instance %s, instance %s has already been registered.",a,this.Sa):(this.Sa=a,this.D=new Q(this.o,a,b),this.ia&&(this.ia(),this.ia=null))};h.updateConsentInstanceState=function(a,b,c){this.D?(this.D.update(a,b,c,!1),this.wa&&this.wa(F(a,b,c))):x().error("CONSENT-STATE-MANAGER","instance not registered")};
h.getLastConsentInstanceInfo=function(){return this.D.get()};h.getConsentInstanceInfo=function(){return this.D.get().then(function(a){return E(a)?F(5):a})};h.onConsentStateChange=function(a){this.wa=a;this.getConsentInstanceInfo().then(function(b){a(b)})};h.setConsentInstanceSharedData=function(a){this.D.sharedDataPromise=a};h.setDirtyBit=function(){this.D.setDirtyBit()};h.getConsentInstanceSharedData=function(){return this.D.sharedDataPromise};
h.whenConsentReady=function(){if(this.D)return H();if(!this.xa){var a=new p;this.xa=a.promise;this.ia=a.resolve}return this.xa};h.mb=function(){return this.D.ba};function Q(a,b,c){this.o=a;this.fb=b;this.sharedDataPromise=null;this.Xa=P(a,"storage");this.ba=this.l=null;this.R="amp-consent:"+b;(this.na=c.onUpdateHref||null)&&Na(this.na,"AMP-CONSENT");this.Aa=void 0}
Q.prototype.setDirtyBit=function(){var a=this;this.Aa=!0;return this.get().then(function(b){E(b)||a.update(b.consentState,b.consentString,b.consentMetadata,!0)})};Q.prototype.update=function(a,b,c,d){var e=a;var f=this.l&&this.l.consentState;r(xa,e)||(e=5);e=3==e?f||5:4==e&&f&&5!=f?f:e;if(3===a)this.l=F(e,this.l&&this.l.consentString,this.l&&this.l.consentMetadata);else{a=this.l;d&&E(a)?this.l=F(e,b,c,!0):this.l=F(e,b,c);var g=F(e,b,c,this.Aa);za(g,this.ba)||nb(this,g)}};
function nb(a,b){a.Xa.then(function(c){if(za(b,a.l,a.Aa))if(5===b.consentState)c.remove(a.R);else{a:{var d=B();var e=b.consentState;if(1==e)d.s=1;else if(2==e)d.s=0;else{d=null;break a}b.consentString&&(d.r=b.consentString);!0===b.isDirty&&(d.d=1);if(b.consentMetadata){e=b.consentMetadata;var f=B();e.consentStringType&&(f.cst=e.consentStringType);e.additionalConsent&&(f.ac=e.additionalConsent);void 0!=e.gdprApplies&&(f.ga=e.gdprApplies);d.m=f}d=0==Object.keys(d)?null:d}if(null!=d){e={};if(1200<JSON.stringify(C((e[a.R]=
d,e))).length){if(c.isViewerStorage()){v().error("CONSENT-STATE-MANAGER","Cannot store consent information which length exceeds %s. Previous stored consentInfo will be cleared",1200);c.remove(a.R);return}v().info("CONSENT-STATE-MANAGER","Current consent information length exceeds %s and will not be stored when the page is served from a viewer that supports the Local Storage API.",1200)}a.ba=b;c.setNonBoolean(a.R,d);ob(a,b)}}})}
Q.prototype.get=function(){var a=this;if(this.l)return Promise.resolve(this.l);var b;return this.Xa.then(function(c){b=c;return b.get(a.R)}).then(function(c){if(a.l)return a.l;if(void 0===c)var d=F(5,void 0,void 0,void 0);else if("boolean"===typeof c)d=Ba(c),d=F(d);else{if(!q(c))throw x().createError("Invalid stored consent value");d=Ba(c.s);var e=c.r;var f=(f=c.m)?Aa(f.cst,f.ac,f.ga):Aa();d=F(d,e,f,c.d&&1===c.d)}a.ba=d;E(d)&&(ob(a,F(5)),b.remove(a.R),a.ba=null);a.l=d;return a.l}).catch(function(a){x().error("CONSENT-STATE-MANAGER",
"Failed to read storage",a);return F(5)})};
function ob(a,b){if(a.na&&!E(b)){var c=ya(b.consentState);fb(a.o).then(function(d){var e={consentInstanceId:a.fb,ampUserId:d};null!=c&&(e.consentState=c);e.consentStateValue=G(b.consentState);b.consentString&&(e.consentString=b.consentString);b.consentMetadata&&(e.consentMetadata=b.consentMetadata);var f={credentials:"include",method:"POST",body:e,ampCors:!1};a.o.whenFirstVisible().then(function(){eb(a.o.getHeadNode(),a.na).then(function(b){N(a.o.win,"xhr").fetchJson(b,f)})})})}};var R;var S,pb="Webkit webkit Moz moz ms O o".split(" ");function rb(a,b,c){if(D(b,"--"))return b;S||(S=B());var d=S[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<pb.length;f++){var g=pb[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(S[b]=d)}return d}function sb(a,b,c){(b=rb(a.style,b,void 0))&&(D(b,"--")?a.style.setProperty(b,c):a.style[b]=c)}
function T(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var tb=['<svg viewBox="0 0 40 40"><defs><linearGradient id=grad><stop stop-color="rgb(105, 105, 105)"></stop><stop offset=100% stop-color="rgb(105, 105, 105)" stop-opacity=0></stop></linearGradient></defs><path d="M11,4.4 A18,18, 0,1,0, 38,20" stroke=url(#grad)></path></svg>'];
function U(a,b,c){this.C=a;this.ma=this.Ea=this.Fa=this.X=this.Da=!1;this.h=null;this.oa=b.uiConfig&&!0===b.uiConfig.overlay;this.bb=b.captions&&b.captions.consentPromptCaption||"User Consent Prompt";this.Za=b.captions&&b.captions.buttonActionCaption||"Focus Prompt";this.Wa=!1;this.P=!0;this.U=this.sa=this.Y=null;this.o=a.getAmpDoc();this.ca=O(this.o,"viewport");this.Ya=O(this.o,"viewer");this.j=a.element;this.S=a.win;this.M=this.S.document;this.aa=this.Na=this.Ba=null;this.J="30vh";this.ua=!0;this.Ca=
this.G=!1;this.Ma=this.eb.bind(this);this.Ha=null;this.W(b,c)}
U.prototype.W=function(a,b){if(b){var c=this.o.getElementById(b);c||v().error("amp-consent-ui","postPromptUI element with id=%s not found",b);this.h=c;this.X=!0}else{var d=a.promptUI,e=a.promptUISrc;if(d){var f=this.o.getElementById(d);f&&this.j.contains(f)||v().error("amp-consent-ui","child element of <amp-consent> with promptUI id %s not found",d);this.h=f}else if(e){this.Da=!0;Na(e,this.j);this.Ha=eb(this.j,e);b=this.j.ownerDocument.createElement("iframe");var g=["allow-scripts","allow-popups"],
k=Ra(this.j,"url"),n=k.parse(e);k=k.parse(this.o.getUrl());n.origin!=k.origin&&g.push("allow-same-origin");b.setAttribute("sandbox",g.join(" "));b.classList.add("i-amphtml-consent-ui-fill");this.h=b;b=this.j.ownerDocument.createElement("placeholder");T(b,!1);b.classList.add("i-amphtml-consent-ui-placeholder");g=b.ownerDocument||b;R&&R.ownerDocument===g||(R=g.createElement("div"));g=R;g.innerHTML=tb[0];n=g.firstElementChild;g.removeChild(n);b.appendChild(n);this.aa=b;this.Na=a.clientConfig||null}}};
U.prototype.show=function(a){var b=this;if(this.h)if(this.X&&!this.j.contains(this.h))T(this.h,!0);else{T(this.j,!0);var c=this.j.classList;c.add("amp-active");c.remove("amp-hidden");this.C.getViewport().addToFixedLayer(this.j);if(this.Da&&this.Ha)this.Ca=a,ub(this).then(function(){b.C.mutateElement(function(){b.X||(b.U=b.M.activeElement);vb(b);wb(b);xb(b)})});else{var d=function(){b.h&&(T(b.h,!0),b.X||(b.U=b.M.activeElement,vb(b),O(b.C.element,"owners").scheduleLayout(b.C.element,b.h),b.h.focus()))};
ua(this.h)?va(this.h).then(function(){return b.h.whenBuilt()}).then(function(){return d()}):d()}this.Fa=!0}};
U.prototype.hide=function(){var a=this;this.h&&this.C.mutateElement(function(){if(a.Da){var b=a.j.classList;b.remove("i-amphtml-consent-ui-iframe-active");b.remove("i-amphtml-consent-ui-modal");b.remove("i-amphtml-consent-ui-border-enabled");a.S.removeEventListener("message",a.Ma);b.remove("i-amphtml-consent-ui-iframe-fullscreen");a.ma?a.Ya.sendMessage("cancelFullOverlay",{},!0):a.G&&a.ca.leaveLightboxMode();a.ma=!1;b.remove("i-amphtml-consent-ui-in");a.Ea=!1;a.h.removeAttribute("name");T(a.aa,!1);
b=a.h;b.parentElement&&b.parentElement.removeChild(b)}a.X||(b=a.j.classList,b.remove("amp-active"),b.add("amp-hidden"));a.oa&&(a.Y&&T(a.Y,!1),yb(a));a.sa&&(b=a.sa,b.parentElement&&b.parentElement.removeChild(b),delete a.sa);yb(a);zb(a);a.C.getViewport().removeFromFixedLayer(a.j);T(a.h,!1);a.Fa=!1;a.U?(a.U.focus(),a.U=null):0<a.S.document.body.children.length&&a.S.document.body.children[0].focus()})};
function Ab(a,b){a.J="30vh";a.ua=!0;a.G=!1;if(b.initialHeight)if("string"===typeof b.initialHeight&&0<=b.initialHeight.indexOf("vh")){var c=parseInt(b.initialHeight,10);a.J=80<=c?"80vh":a.J;10<=c&&80>=c?(a.J=c+"vh",a.G=60<c,a.oa=a.G||a.oa):v().error("amp-consent-ui","Inavlid initial height: "+b.initialHeight+".Minimum: 10vh. Maximum: 80vh.")}else v().error("amp-consent-ui","Inavlid initial height: "+b.initialHeight+'.Must be a string in "vh" units.');!1!==b.border||a.G||(a.ua=!1);a.Ba.resolve()}
function Bb(a){return P(a.o,"consentStateManager").then(function(b){return b.getLastConsentInstanceInfo().then(function(b){return C({clientConfig:a.Na,consentState:G(b.consentState),consentStateValue:G(b.consentState),consentMetadata:b.consentMetadata,consentString:b.consentString,promptTrigger:a.Ca?"action":"load",isDirty:!!b.isDirty})})})}
function ub(a){a.Ba=new p;var b=a.j.classList;sa(a.j)||ra(a.j,a.aa);b.add("i-amphtml-consent-ui-loading");T(a.h,!1);var c=a.Ha.then(function(b){a.h.src=b;return Bb(a).then(function(b){a.h.setAttribute("name",JSON.stringify(b));a.S.addEventListener("message",a.Ma);ra(a.j,a.h)})});return Promise.all([c,a.Ba.promise,a.C.mutateElement(function(){T(a.aa,!0)})])}
function xb(a){var b=a.j.classList;b.add("i-amphtml-consent-ui-iframe-active");a.G&&b.add("i-amphtml-consent-ui-modal");T(a.aa,!1);T(a.h,!0);zb(a);a.C.mutateElement(function(){b.remove("i-amphtml-consent-ui-loading");a.C.mutateElement(function(){b.add("i-amphtml-consent-ui-in");a.Ea=!0;if(a.h){var c=a.h,d={height:a.J},e;for(e in d)sb(c,e,d[e])}c={transform:"translate3d(0px, calc(100% - "+a.J+"), 0px)","--i-amphtml-modal-height":""+a.J};d=a.j.style;for(var f in c)d.setProperty(rb(d,f),c[f].toString(),
"important");(a.ua||a.G)&&a.j.classList.add("i-amphtml-consent-ui-border-enabled");a.G&&a.ca.enterLightboxMode()})})}
function wb(a){if(!a.Wa){var b=a.M.createElement("div"),c=a.M.createElement("button"),d=a.M.createElement("div");b.setAttribute("role","alertdialog");d.textContent=a.bb;c.textContent=a.Za;c.onclick=function(){try{a.h.focus()}catch(e){}};b.appendChild(d);b.appendChild(c);b.classList.add("i-amphtml-consent-alertdialog");a.C.element.appendChild(b);try{c.focus()}catch(e){}a.Wa=!0;a.sa=b}}function zb(a){a=a.j;var b={transform:"",transition:""},c;for(c in b)sb(a,c,b[c])}
function vb(a){if(a.oa){if(!a.Y){var b=a.S.document.createElement("div");b.classList.add("i-amphtml-consent-ui-mask");a.j.ownerDocument.body.appendChild(b);a.Y=b}T(a.Y,!0);a.P&&(a.ca.enterOverlayMode(),a.P=!1)}}function yb(a){a.P||(a.ca.leaveOverlayMode(),a.P=!0)}
U.prototype.eb=function(a){var b=this;if(this.h.contentWindow===a.source&&(a=a.data)&&"consent-ui"==a.type){var c=a.action,d=a.type;"ready"===c&&Ab(this,a);"enter-fullscreen"===c&&(!this.Ea||this.G||this.M.activeElement!==this.h&&!this.Ca?(v().warn("amp-consent-ui","Could not enter fullscreen. Fullscreen is only supported when the iframe is visible as a bottom sheet and after user interaction."),Cb(this,d,c,!0)):(Cb(this,d,c),this.C.mutateElement(function(){b.h&&b.Fa&&!b.ma&&(zb(b),b.Ya.sendMessage("requestFullOverlay",
{},!0),b.j.classList.add("i-amphtml-consent-ui-iframe-fullscreen"),b.P&&(b.ca.enterOverlayMode(),b.P=!1),b.ma=!0)})))}};function Cb(a,b,c,d){var e=d=void 0===d?!1:d;(a=a.h.contentWindow)&&a.postMessage({type:"amp-consent-response",requestType:b,requestAction:c,state:e?"error":"success",info:e?"Could not enter fullscreen. Fullscreen is only supported when the iframe is visible as a bottom sheet and after user interaction.":"Entering fullscreen."},"*")};function V(){this.O=0;this.Va=H();this.Ta=function(){};this.Ua=function(){}}V.prototype.onQueueEmpty=function(a){this.Ta=a;0==this.O&&a()};V.prototype.onQueueNotEmpty=function(a){this.Ua=a;0<this.O&&a()};V.prototype.registerUI=function(a){var b=this;0==this.O&&this.Ua();this.O++;var c=this.Va.then(function(){return a().then(function(){b.O--;0==b.O&&b.Ta()})});return this.Va=c};var Db={ACCEPT:"accept",REJECT:"reject",DISMISS:"dismiss"};function W(a){a=AMP.BaseElement.call(this,a)||this;a.w=null;a.ha=null;a.$=null;a.ka=null;a.A=null;a.Ga=null;a.pa=null;a.la=null;a.L=!1;a.Ra=!1;a.ya=!1;a.Ka=a.getVsync();a.ra=null;a.T=null;a.Z=null;return a}var X=AMP.BaseElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;
if(ea)ea(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Eb=Object.getOwnPropertyDescriptor(X,Y);Eb&&Object.defineProperty(W,Y,Eb)}else W[Y]=X[Y];W.nb=X.prototype;h=W.prototype;h.getConsentPolicy=function(){return null};h.buildCallback=function(){var a=this;y(this.element.getAttribute("id"),"amp-consent should have an id");var b=new Za(this.element);return b.getConsentConfigPromise().then(function(c){a.Z=b.getMatchedGeoGroup();Fb(a,c)})};
function Fb(a,b){a.A=b;a.T=a.A.consentInstanceId;a.A.postPromptUI&&(a.pa=new U(a,C({}),a.A.postPromptUI));b=a.A.policy||C({});a.Ga=gb(b,a.T);b=a.getRealChildren();for(var c=0;c<b.length;c++){var d=b[c];T(d,!1);O(a.element,"owners").setOwner(d,a.element)}var e=P(a.getAmpDoc(),"consentPolicyManager").then(function(b){a.ha=b;a.ha.setLegacyConsentInstanceId(a.T);var c=Object.keys(a.Ga);for(b=0;b<c.length;b++)a.ha.registerConsentPolicyInstance(c[b],a.Ga[c[b]])}),f=P(a.getAmpDoc(),"consentStateManager").then(function(b){b.registerConsentInstance(a.T,
a.A);a.w=b}),g=P(a.getAmpDoc(),"notificationUIManager").then(function(b){a.$=b});Promise.all([f,g,e]).then(function(){a.W()})}function Gb(a){a.registerAction("accept",function(){Z(a,"accept")});a.registerAction("reject",function(){Z(a,"reject")});a.registerAction("dismiss",function(){Z(a,"dismiss")});a.registerAction("prompt",function(b){var c=b.args;c&&!0===c.expireCache&&a.w.setDirtyBit();Hb(a,!0)});Ib(a)}
function Ib(a){a.win.addEventListener("message",function(b){if(a.L){var c=b.data;if(c&&"consent-response"==c.type)if(c.action){if(void 0!==c.info){"string"!=typeof c.info&&(v().error("amp-consent","consent-response info only supports string, %s, treated as undefined",c.info),c.info=void 0);"dismiss"===c.action&&(c.info&&a.user().error("amp-consent","Consent string value %s not applicable on user dismiss, stored value will be kept and used",d),c.info=void 0);var d=c.info;var e=Jb(c.consentMetadata,
d)}for(var f=a.element.querySelectorAll("iframe"),g=0;g<f.length;g++)if(f[g].contentWindow===b.source){Z(a,c.action,d,e);break}}else v().error("amp-consent","consent-response message missing required info")}})}function Hb(a,b){a.$||x().error("amp-consent","notification ui manager not found");!a.ya&&a.ka&&(a.ya=!0,a.$.registerUI(a.hb.bind(a,b)))}
h.hb=function(a){var b=this;this.L&&x().error("amp-consent","Attempt to show an already displayed prompt UI");this.Ka.mutate(function(){b.ka.show(a);b.L=!0});var c=new p;this.la=c.resolve;return c.promise};
function Z(a,b,c,d){r(Db,b)&&a.L&&(a.w?(a.Ra=!0,"accept"==b?a.w.updateConsentInstanceState(1,c,d):"reject"==b?a.w.updateConsentInstanceState(2,c,d):"dismiss"==b&&a.w.updateConsentInstanceState(3),a.L||x().error("amp-consent","%s no consent ui to hide"),a.ka.hide(),a.L=!1,a.la&&(a.la(),a.la=null),a.ya=!1):x().error("amp-consent","No consent state manager"))}
h.W=function(){var a=this;Kb(this);Lb(this);Mb(this).then(function(b){return Nb(a,b)}).then(function(b){b&&Ob(a);a.ha.enableTimeout()}).catch(function(){});Gb(this)};function Mb(a){return a.w.getConsentInstanceInfo().then(function(b){if(Ca(b))return Promise.resolve(!0);var c=a.A.consentRequired;return"boolean"===typeof c?Promise.resolve(c):Pb(a).then(function(a){return a?void 0!==a.consentRequired?!!a.consentRequired:!!a.promptIfUnknown:!1})})}
function Kb(a){var b=Pb(a).then(function(a){return a&&void 0!==a.sharedData?a.sharedData:null});a.w.setConsentInstanceSharedData(b)}function Lb(a){Pb(a).then(function(b){if(b&&((b.expireCache||b.forcePromptOnNext)&&a.w.setDirtyBit(),b.consentRequired&&!a.Ra)){var c=b.consentString||void 0,d=b.consentMetadata||void 0;b=b.consentStateValue;b="accepted"===b?1:"rejected"===b?2:"unknown"===b?5:null;null!==b&&a.w.updateConsentInstanceState(b,c,Jb(d,c))}})}
function Pb(a){if(a.ra)return a.ra;a.ra=a.A.checkConsentHref?a.w.getLastConsentInstanceInfo().then(function(b){b={consentInstanceId:a.T,consentStateValue:G(b.consentState),consentMetadata:b.consentMetadata,consentString:b.consentString,isDirty:!!b.isDirty,matchedGeoGroup:a.Z};a.A.clientConfig&&(b.clientConfig=a.A.clientConfig);var c={credentials:"include",method:"POST",body:b},d=a.A.checkConsentHref;Na(d,a.element);b=a.getAmpDoc();var e=Oa(b.getUrl()),f=Pa(d,e),g=N(a.win,"xhr");return b.whenFirstVisible().then(function(){return eb(a.element,
f).then(function(b){return g.fetchJson(b,c).then(function(b){try{return g.xssiJson(b,a.A.xssiPrefix)}catch(w){y(!1,"Could not parse the `checkConsentHref` response.")}})})})}):Promise.resolve(null);return a.ra}function Nb(a,b){a.ka=new U(a,a.A);return a.w.getConsentInstanceInfo().then(function(c){if(Ca(c))return!0;if(!b)return a.w.updateConsentInstanceState(4),!1;Hb(a,!1);return!0})}
function Ob(a){a.pa&&(a.$.onQueueEmpty(function(){a.Ka.mutate(function(){a.pa.show(!1)})}),a.$.onQueueNotEmpty(function(){a.Ka.mutate(function(){a.pa.hide()})}))}h.kb=function(){return this.w};h.jb=function(){return Mb(this)};h.lb=function(){return this.L};
function Jb(a,b){if(a){if(q(a)&&b){var c=a.consentStringType,d=a.additionalConsent,e=a.gdprApplies;b=[];c&&!r(fa,c)&&(delete a.consentStringType,b.push("consentStringType"));d&&"string"!=typeof d&&(delete a.additionalConsent,b.push("additionalConsent"));e&&"boolean"!=typeof e&&(delete a.gdprApplies,b.push("gdprApplies"));for(c=0;c<b.length;c++)v().error("amp-consent",'Consent metadata value "%s" is invalid.',b[c]);return Aa(a.consentStringType,a.additionalConsent,a.gdprApplies)}v().error("amp-consent",
"CMP metadata is invalid or no consent string is found.")}}
(function(a){a.registerElement("amp-consent",W,"amp-consent{position:fixed!important;bottom:0;left:0;overflow:hidden!important;background:hsla(0,0%,100%,0.7);width:100%;z-index:2147483645}amp-consent[i-amphtml-notbuilt]>*{display:none!important}amp-consent>*{max-height:100vh!important}amp-consent.amp-active{visibility:visible}amp-consent.amp-hidden{visibility:hidden}@keyframes amp-consent-ui-placeholder-spin{0%{transform:rotate(0deg)}to{transform:rotate(360deg)}}.i-amphtml-consent-ui-placeholder{width:100%;height:100%;display:-ms-flexbox;display:flex;-ms-flex-pack:center;justify-content:center;-ms-flex-align:center;align-items:center}.i-amphtml-consent-ui-placeholder>svg{width:30px;height:30px;fill:none;stroke-width:1.5px;transform-origin:50% 50%;animation:amp-consent-ui-placeholder-spin 1000ms linear infinite}.i-amphtml-consent-alertdialog{overflow:hidden;position:absolute;height:1px;width:1px;top:auto;left:auto}.i-amphtml-consent-ui-fill{position:absolute;top:0;left:0;width:100%}iframe.i-amphtml-consent-ui-fill{border:none}amp-consent.i-amphtml-consent-ui-iframe-active{width:100%!important;height:100%!important;padding:0px!important;margin:0px!important;overflow:auto!important;transform:translate3d(0px,100vh,0px)!important}amp-consent.i-amphtml-consent-ui-iframe-active.i-amphtml-consent-ui-modal{box-sizing:border-box;top:0;right:0;animation:i-amphtml-modal-appear 0.5s;animation-fill-mode:forwards;height:var(--i-amphtml-modal-height)!important;width:90vw!important;margin:auto!important;max-width:760px}amp-consent.i-amphtml-consent-ui-border-enabled{border-top-left-radius:8px!important;border-top-right-radius:8px!important;box-shadow:0 0 5px 0 rgba(0,0,0,0.2)!important}amp-consent.i-amphtml-consent-ui-modal.i-amphtml-consent-ui-border-enabled{border-radius:8px!important;box-shadow:0 0 5px 0 rgba(0,0,0,0.2)!important}amp-consent.i-amphtml-consent-ui-iframe-active.i-amphtml-consent-ui-in{transition:transform 0.5s ease-out!important}amp-consent.i-amphtml-consent-ui-iframe-active.i-amphtml-consent-ui-in.i-amphtml-consent-ui-iframe-fullscreen{top:0px!important;transform:translateZ(0px)!important;border-top-left-radius:0px!important;border-top-right-radius:0px!important}amp-consent.i-amphtml-consent-ui-in.i-amphtml-consent-ui-iframe-fullscreen>.i-amphtml-consent-ui-fill{height:100%!important}@keyframes i-amphtml-consent-ui-mask{0%{opacity:0.0}to{opacity:0.2}}@keyframes i-amphtml-modal-appear{0%{transform:translateY(100vh);opacity:0}to{transform:translate(0);opacity:1}}.i-amphtml-consent-ui-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;animation:i-amphtml-consent-ui-mask 0.25s ease-in;background-image:none!important;background-color:#000;z-index:2147483644}\n/*# sourceURL=/extensions/amp-consent/0.1/amp-consent.css*/");a.registerServiceForDoc("notificationUIManager",
V);a.registerServiceForDoc("consentStateManager",mb);a.registerServiceForDoc("consentPolicyManager",jb)})(self.AMP);
})});

//# sourceMappingURL=MisterOperator-consent-0.1.js.map
