(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"2009252320001",f:(function(AMP,_){
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ca=ba(this);"function"===typeof Symbol&&Symbol("x");var da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.La=b.prototype};function ka(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function p(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma="";
function q(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=p(a.location.originalHash||a.location.hash);var c=p(a.location.search);ma||(ma=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012009252320001");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2009252320001",rtvVersion:ma};b=a.__AMP_MODE=b}return b}
;var na=Object.prototype.toString;function v(a){return a?Array.prototype.slice.call(a):[]}function x(a){return"[object Object]"===na.call(a)};var y=self.AMP_CONFIG||{},oa=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var z={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||pa("amp-geo-api")};function qa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function C(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}
function D(a,b,c,d,e){return B().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var ra=Object.prototype.hasOwnProperty;function F(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function G(a){return a||{}}function H(a,b){if(ra.call(a,b))return a[b]}
function sa(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(a={};0<d.length;){b=d.shift();a.F=b.t;a.B=b.s;a.O=b.d;if(c.includes(a.B))throw Error("Source object has a circular reference.");c.push(a.B);a.F!==a.B&&(10<a.O?Object.assign(a.F,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(ra.call(a.F,b)){var e=a.F[b];if(x(c)&&x(e)){d.push({t:e,s:c,d:a.O+1});return}}a.F[b]=c}}(a)));a={B:a.B,F:a.F,O:a.O}}};function I(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function ta(a,b){var c=a.ownerDocument.defaultView,d=J(c),e=c!=d,f=ua(d);e&&!f?b=K(c,b)?L(c,b):null:(a=M(a),a=N(a),b=K(a,b)?L(a,b):null);return b}function va(a,b){var c=J(a);K(a,"bind");if(ua(c)){var d=M(a.document);wa(N(d),d,"bind",function(){return b},!0)}else wa(a,a,"bind",function(){return b}),L(a,"bind")}function O(a,b){a=J(a);return L(a,b)}function P(a,b){var c=M(a);c=N(c);return L(c,b)}function J(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}
function M(a){return a.nodeType?O((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function N(a){a=M(a);return a.isSingleDoc()?a.win:a}function L(a,b){K(a,b);a=xa(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function wa(a,b,c,d,e){var f=xa(a),g=f[c];g||(g=f[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});if(e||!g.ctor&&!g.obj)g.ctor=d,g.context=b,g.resolve&&L(a,c)}
function ya(a,b){var c=za(a,b);if(c)return c;a=xa(a);a[b]=Aa();return a[b].promise}function za(a,b){var c=xa(a)[b];if(c){if(c.promise)return c.promise;L(a,b);return c.promise=Promise.resolve(c.obj)}return null}function xa(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function K(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Aa(){var a=new I,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Ba(){this.va=100;this.W=this.aa=0;this.P=Object.create(null)}Ba.prototype.has=function(a){return!!this.P[a]};Ba.prototype.get=function(a){var b=this.P[a];if(b)return b.access=++this.W,b.payload};Ba.prototype.put=function(a,b){this.has(a)||this.aa++;this.P[a]={payload:b,access:this.W};if(!(this.aa<=this.va)){C().warn("lru-cache","Trimming LRU cache");a=this.P;var c=this.W+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.aa--)}};function Q(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var Ca=G({c:!0,v:!0,a:!0,ad:!0}),Da,Ea,Fa=/[?&]amp_js[^&]*/,Ga=/[?&]amp_gsa[^&]*/,Ha=/[?&]amp_r[^&]*/,Ka=/[?&]amp_kit[^&]*/,La=/[?&]usqp[^&]*/;
function R(a){Da||(Da=self.document.createElement("a"),Ea=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new Ba));var b=Ea,c=Da;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function Ma(a,b){var c=void 0===c?"source":c;D(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=R(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);D(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}
function S(a){"string"==typeof a&&(a=R(a));return z.cdnProxyRegex.test(a.origin)}
function Na(a){"string"==typeof a&&(a=R(a));if(!S(a))return a.href;var b=a.pathname.split("/");D(Ca[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);D(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Fa,"").replace(Ga,"").replace(Ha,"").replace(Ka,"").replace(La,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Oa(a,b){"string"==typeof b&&(b=R(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=R(d));c=c.replace(/\\/g,"/");var e=R(c);c=Q(c.toLowerCase(),e.protocol)?e.href:Q(c,"//")?d.protocol+c:Q(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Pa(a){var b=R(a),c=p(b.search);D(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function ua(a){if(a.__AMP__EXPERIMENT_TOGGLES)var b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){d=
d.getAttribute("content").split(",");for(var e=0;e<d.length;e++)-1!=c.indexOf(d[e])&&(b[d[e]]=!0)}Object.assign(b,Qa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(c=a.AMP_CONFIG["allow-url-opt-in"],a=p(a.location.originalHash||a.location.hash),d=0;d<c.length;d++)e=a["e-"+c[d]],"1"==e&&(b[c[d]]=!0),"0"==e&&(b[c[d]]=!1)}return!!b["ampdoc-fie"]}
function Qa(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){C().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var Ra,Sa="Webkit webkit Moz moz ms O o".split(" ");function Ta(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ua(){return AMP.BaseElement.apply(this,arguments)||this}ja(Ua,AMP.BaseElement);k=Ua.prototype;k.getLayoutPriority=function(){return 1};k.isAlwaysFixed=function(){return!0};k.isLayoutSupported=function(){return!0};k.renderOutsideViewport=function(){return!0};k.L=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};var Va;function T(){return Va?Va:Va=Promise.resolve(void 0)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Wa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Xa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Ya(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Za(a,b){Ya(a.documentElement,function(){return!!a.body},b)}function $a(a){return new Promise(function(b){return Za(a,b)})}function ab(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}
function bb(a,b){return a.closest?a.closest(b):ab(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function cb(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function db(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function eb(a){Q(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new I;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function fb(a){var b=za(N(a),"bind");if(b)return b;var c=M(a);return c.waitForBodyOpen().then(function(){return gb(c.win,c.win.document.head)}).then(function(){var b=c.win;return b.__AMP_EXTENDED_ELEMENTS&&b.__AMP_EXTENDED_ELEMENTS["amp-bind"]?ya(N(a),"bind"):null})}function hb(a){var b=ta(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=J(b);return b!==c?ib(b):fb(a)}
function gb(a,b){if(b){var c={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var d=0;d<b.length;d++){var e=b[d];e=e.getAttribute("custom-element")||e.getAttribute("custom-template");c[e]=!0}c=Object.keys(c)}else c=[];return c.includes("amp-bind")?O(a,"extensions").waitForExtension(a,"amp-bind"):T()}
function ib(a){return $a(a.document).then(function(){return gb(a,a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?ya(a,"bind"):null})};function jb(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function kb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function lb(a,b){if(!isFinite(20))throw Error("Invalid depth: 20");if(a===b)return!0;for(a=[{a:a,b:b,depth:20}];0<a.length;){var c=a.shift();b=c.a;var d=c.b;c=c.depth;if(0<c){if(typeof b!==typeof d)return!1;if(Array.isArray(b)&&Array.isArray(d)){if(b.length!==d.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:d[e],depth:c-1});continue}else if(b&&d&&"object"===typeof b&&"object"===typeof d){var f=Object.keys(b),g=Object.keys(d);if(f.length!==g.length)return!1;for(e=0;e<f.length;e++){var l=
f[e];a.push({a:b[l],b:d[l],depth:c-1})}continue}}if(b!==d)return!1}return!0};function mb(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Ma(b.getAttribute("src"),b);var l=O(a.win,"batched-xhr");return nb(b,e,f).then(function(a){return l.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return O(a.win,"xhr").xssiJson(b,g)}).then(function(a){if(null==a)throw Error("Response is undefined.");return jb(a,d||".")}).catch(function(a){throw B().createError("failed fetching JSON data",
a);})}
function nb(a,b,c){var d=a.getAttribute("src"),e=ta(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectDisallowedVarsSync(a);if(0<f.length)throw B().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(f.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var l={};a.hasAttribute("credentials")&&(l.credentials=a.getAttribute("credentials"));c&&
(l.cache="reload");return{xhrUrl:d,fetchOpt:l}})};function ob(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function pb(a){a=AMP.BaseElement.call(this,a)||this;a.R=void 0;a.$=new I;return a}ja(pb,AMP.BaseElement);k=pb.prototype;k.getLayoutPriority=function(){return 1};k.isAlwaysFixed=function(){return!0};k.isLayoutSupported=function(){return!0};
k.buildCallback=function(){var a=this;Ta(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&hb(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&qb(this,!0);this.registerAction("refresh",function(){D(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');qb(a,!1,!0)})};
k.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&qb(this,!1);else{var b=this.L();C().error(b,"ampdoc must be visible before mutation.")}};k.renderOutsideViewport=function(){return!0};k.parseAndUpdate=function(){return void 0===this.R&&(this.R=rb(this),null!==this.R)?sb(this,this.R,!0):T()};
function rb(a){var b=a.element.children;if(0==b.length)return null;var c=a.L();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return db(d)?kb(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function wb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src");f=R(Na(f)).origin===R(Na(e.win.location)).origin||b?2:1;return mb(e,a.element,{urlReplacement:f,refresh:c}).catch(function(b){b=b?ob(a.win,"amp-state.error",G({response:b.response})):null;ta(d,"action").trigger(d,"fetch-error",b,1)})}
function qb(a,b,c){b||(a.$=new I);var d=a.$;a.getAmpDoc().whenFirstVisible().then(function(){return wb(a,b,c)}).then(function(c){return sb(a,c,b)}).then(function(){return d.resolve()}).catch(function(a){d.resolve();throw a;})}k.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.$.promise:T()};
function sb(a,b,c){if(void 0===b||null===b)return T();var d=D(a.element.id,"<amp-state> must have an id.");return hb(a.element).then(function(a){var e=F();e[d]=b;a.setState(e,{skipEval:c,skipAmpState:!c})})}k.L=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var xb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function yb(a){for(var b=[],c;c=xb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new zb(b)}
function zb(a){D(0<a.length,"Srcset must have at least one source");this.N=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}D(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Ab:Bb);this.ra=b}
zb.prototype.select=function(a,b){if(this.ra){b*=a;a=this.N;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,l=Math.abs(g-b);if(l<=1.1*d||1.2<b/e)c=f,d=l,e=g;else break}b=c}else{a=this.N;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.N[b].url};zb.prototype.getUrls=function(){return this.N.map(function(a){return a.url})};
zb.prototype.stringify=function(a){for(var b=[],c=this.N,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ra?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function Ab(a,b){D(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Bb(a,b){D(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Cb={"class":{denylistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Db={width:null,height:null},Eb={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{denylistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null},SELECT:{autofocus:null,disabled:null,
multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Fb={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function Gb(a){this.ta=a}Gb.prototype.canBind=function(a,b){return void 0!==Hb(this,a,b)};
Gb.prototype.isResultValid=function(a,b,c){var d=Hb(this,a,b);d&&d.alternativeName&&(d=Hb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&H(Fb,b)){if("srcset"===b){try{var e=yb(c)}catch(l){return B().error("amp-bind","Failed to parse srcset: ",l),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{e=f[a];b=d;if(e){if(/__amp_source_origin/.test(e)){b=!1;break a}if(b=b.allowedProtocols)if(e=/^([^:\/?#.]+):[\s\S]*$/.exec(e),null!==e&&(e=e[1].toLowerCase().trim(),!ra.call(b,
e))){b=!1;break a}}b=!0}if(!b)return!1}}var g=d.denylistedValueRegex;return c&&g&&(new RegExp(g,"i")).test(c)?!1:!0};function Hb(a,b,c){if(Q(c,"aria-"))return null;if(!H(Fb,c)||a.ta){var d=H(Cb,c);if(void 0!==d)return d;var e=H(Db,c);if(Q(b,"AMP-")&&void 0!==e)return e;var f=H(Eb,b);if(f)return f[c]}};var Ib=!1;function Jb(a){if(!Ib){Ib=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(Q(g,"--"))f=g;else{Ra||(Ra=F());var l=Ra[g];if(!l){l=g;if(void 0===f[g]){var n=g;n=n.charAt(0).toUpperCase()+n.slice(1);b:{for(var h=0;h<Sa.length;h++){var r=Sa[h]+n;if(void 0!==f[r]){n=r;break b}}n=""}void 0!==f[n]&&(l=n)}Ra[g]=l}f=l}f&&(Q(f,"--")?d.style.setProperty(f,e):d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=-1,d=0,e=this.o.length;d<=e;){c=Math.floor((d+e)/2);if(c===this.o.length)break;if(this.o[c].priority<b)d=c+1;else if(0<c&&this.o[c-1].priority>=b)e=c-1;else break}this.o.splice(c,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ca.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Kb=/nochunking=1/.test(self.location.hash),Lb=T();function Mb(a,b){if(Kb)Lb.then(b);else{var c=Nb,d=M(a),e=N(d);wa(e,d,"chunk",c);P(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Y=a}function Ob(a,b){if("run"!=a.state){a.state="run";try{a.Y(b)}catch(c){throw a.la(),c;}}}V.prototype.L=function(){return this.Y.displayName||this.Y.name};V.prototype.la=function(){};V.prototype.ja=function(){return!1};V.prototype.pa=function(){return!1};function W(a,b,c){V.call(this,a);this.fa=c}
ja(W,V);W.prototype.la=function(){Jb(self.document)};W.prototype.ja=function(){return this.fa.ampdoc.isVisible()};W.prototype.pa=function(){return this.fa.ga};
function Nb(a){var b=this;this.ampdoc=a;this.h=a.win;this.K=new U;this.ea=this.ha.bind(this);this.H=0;this.Da=!(!this.h.navigator.scheduling||!this.h.navigator.scheduling.isInputPending);this.T=!1;this.ua=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ha(null)});this.ga=!1;ya(N(a),"viewer").then(function(){b.ga=!0});a.onVisibilityChanged(function(){a.isVisible()&&Pb(b)})}
Nb.prototype.run=function(a,b){var c=new V(a);this.K.enqueue(c,b);Pb(this)};Nb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.K.enqueue(a,Number.POSITIVE_INFINITY);Pb(this)};function Qb(a,b){for(var c=a.K.peek();c&&"not_run"!==c.state;)a.K.dequeue(),c=a.K.peek();c&&b&&a.K.dequeue();return c}
Nb.prototype.ha=function(a){var b=this,c=Qb(this,!0);if(!c)return this.T=!1,this.H=0,!1;try{var d=Date.now();Ob(c,a)}finally{Lb.then().then().then().then().then().then().then().then().then(function(){b.T=!1;b.H+=Date.now()-d;C().fine("CHUNK",c.L(),"Chunk duration",Date.now()-d,b.H);Pb(b)})}return!0};function Rb(a){a.ua&&(a.Da?a.h.navigator.scheduling.isInputPending():5<a.H)?(a.H=0,Sb(a)):Lb.then(function(){a.ea(null)})}
function Pb(a){if(!a.T){var b=Qb(a);b&&(b.ja()?(a.T=!0,Rb(a)):b.pa()&&a.h.requestIdleCallback?Tb(a.h,a.ea):Sb(a))}}function Sb(a){a.h.postMessage("amp-macro-task","*")}
function Tb(a,b){function c(e){if(15>e.timeRemaining()){var f=2E3-(Date.now()-d);0>=f||e.didTimeout?(C().fine("CHUNK","Timed out",2E3,e.didTimeout),b(e)):(C().fine("CHUNK","Rescheduling with",f,e.timeRemaining()),a.requestIdleCallback(c,{timeout:f}))}else C().fine("CHUNK","Running idle callback with ",15),b(e)}var d=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Ub(){this.D=F();this.j=null}k=Ub.prototype;k.get=function(a){a=this.D[a];return null==a?null:a};k.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.D[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new I,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=F());this.j[a]=b}return b.promise};
k.signal=function(a,b){if(null==this.D[a]){var c=void 0==b?Date.now():b;this.D[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};k.rejectSignal=function(a,b){null==this.D[a]&&(this.D[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.promise.catch(function(){}),a.resolve=void 0,a.reject=void 0))};k.reset=function(a){this.D[a]&&delete this.D[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function Vb(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var l=f;f=null;b.apply(null,l)}}var d=0,e=0,f=null;return function(b){for(var g=[],n=0;n<arguments.length;++n)g[n-0]=arguments[n];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function Wb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function Xb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function Yb(){var a=q().esm?".mjs":".js";var b=z.cdn;return b+"/rtv/"+q().rtvVersion+"/ww"+a};function Zb(a){var b=this;this.h=a;this.Fa=O(a,"xhr");var c=Yb();C().fine("web-worker","Fetching web worker from",c);this.ba=null;this.ia=this.Fa.fetchText(c,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(a){return a.text()}).then(function(d){d=d.replace(/^\/\/# sourceMappingURL=.*/,"//# sourceMappingURL="+(c+".map"));d=new a.Blob([d+"\n//# sourceurl="+c],{type:"text/javascript"});var e=a.URL.createObjectURL(d);b.ba=new a.Worker(e);b.ba.onmessage=b.Ca.bind(b)});this.S={};this.wa=0;this.sa=
[a]}function $b(a,b,c,d){return a.ia.then(function(){return new Promise(function(e,f){var g=a.wa++;a.S[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.sa.indexOf(e);e=0<=f?f:a.sa.push(e)-1;a.ba.postMessage({method:b,args:c,scope:e,id:g})})})}Zb.prototype.Ca=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.S[b];d?(d.resolve(c),delete this.S[b]):C().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Zb.prototype.hasPendingMessages=function(){return 0<Object.keys(this.S).length};Zb.prototype.Ga=function(){return this.ia};function ac(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};function bc(){var a=cc();return function(b){return setTimeout(b,a())}}function cc(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function dc(a){dc=bc();return dc(a)}function ec(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var fc;
function Y(a,b){try{if(a)if(void 0!==a.message)a=qa(a);else{var c=a;a=Error(ec(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),q().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.za&&
d.za("amp:error",a.message);gc.call(self,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function gc(a,b,c,d,e){var f=this;!this||!this.document||e&&e.expected||Jb(this.document);if(!q().development){var g=!1;try{g=hc()}catch(n){}if(!(g&&.01<Math.random())){var l=ic(a,b,c,d,e,g);l&&dc(function(){try{return jc(f,l).catch(function(){})}catch(n){}})}}}
function jc(a,b){return b.pt&&.9>Math.random()?T():kc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",.1>Math.random()?z.betaErrorReporting:z.errorReporting,!0);c.send(JSON.stringify(b))}})}
function kc(a,b){var c=O(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);var d=c.getSingleDoc();if(!d.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var e=P(d,"viewer");return e.hasCapability("errorReporter")?e.isTrustedViewer().then(function(a){if(!a)return!1;e.sendMessage("error",G({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,pt:b.pt,jse:b.jse}));return!0}):Promise.resolve(!1)}
function ic(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var l=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var n=!(self&&self.window),h=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||n)if(l=!0,.001<h)return;var r=0<=a.indexOf("\u200b\u200b\u200b");if(!(r&&.1<h)){g=Object.create(null);g.v=q().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=r?"1":"0";g.ex=l?"1":"0";g.dw=n?"1":"0";var m="1p";self.context&&
self.context.location?(g["3p"]="1",m="3p"):q().runtime&&(m=q().runtime);g.rt=m;"inabox"===m&&(g.adid=q().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var t=self.AMP.viewer.getResolvedViewerUrl(),
E=self.AMP.viewer.maybeGetMessagingOrigin();t&&(g.rvu=t);E&&(g.mso=E)}fc||(fc=lc());g.jse=fc;var w=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var u in f)w.push(u+"="+(f[u]?"1":"0"));g.exps=w.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),r||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";g.ae=X.join(",");g.fr=self.location.originalHash||
self.location.hash;"production"===g.bt&&(g.pt="1");b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function hc(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!S(a[b].src.toLowerCase()))return!0;return!1}
function lc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(Q(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(Q(b,"Error: message"))return"Chrome"}return"unknown"};function mc(a,b,c){var d=self.location;Pa(c);var e=S(d),f=R(Na(d));if("href"==b&&!Q(c,"#"))return Oa(c,f);if("src"==b)return"amp-img"==a?nc(c,f,e):Oa(c,f);if("srcset"==b){try{var g=yb(c)}catch(l){return B().error("URL-REWRITE","Failed to parse srcset: ",l),c}return g.stringify(function(a){return nc(a,f,e)})}return c}
function nc(a,b,c){a=R(Oa(a,b));return"data:"==a.protocol||S(a)||!c?a.href:z.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function oc(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function pc(a,b){var c=oc(a);if(c)b(a);else{var d=function(){oc(a)&&(c||(c=!0,b(a)),a.removeEventListener("readystatechange",d))};a.addEventListener("readystatechange",d)}}function qc(a){return new Promise(function(b){pc(a,b)})};var rc=/^(i?-)?amp(html)?-/,sc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0}},tc=F({"AMP-CAROUSEL":["slide"],"AMP-LIST":["is-layout-container"],"AMP-SELECTOR":["selected"]}),uc=["AMP-LIST"];
function vc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.I=b||a.win;this.X=[];this.Aa=Vb(this.h,function(){c.X.length=0});this.G=[];this.C=F();this.Z=P(a,"history");this.ma=[];this.J=1E3;this.ka=P(a,"mutator");this.w=F();this.Ea=O(this.h,"timer");this.qa=null;this.V=P(this.ampdoc,"viewer");this.V.onMessageRespond("premutate",this.Ba.bind(this));this.na=a.whenFirstVisible().then(function(){if(b){var c=b.document;return qc(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})});
this.M=this.na.then(function(a){return wc(c,a)});this.da=new I;this.U=null;this.oa=new Ub;var d=self.AMP;d.printState=d.printState||this.ya.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.xa.bind(this)}vc.installInEmbedWindow=function(a,b){va(a,new vc(b,a))};k=vc.prototype;k.signals=function(){return this.oa};
k.setState=function(a,b){var c=this,d=b=void 0===b?{}:b;C().info("amp-bind","setState (init=%s):",d.skipEval,a);try{sa(this.w,a)}catch(e){B().error("amp-bind","Failed to merge result from AMP.setState().",e)}return d.skipEval?T():this.U=this.M.then(function(){return xc(c)}).then(function(a){return yc(c,a,{skipAmpState:d.skipAmpState,constrain:d.constrain})})};
k.invoke=function(a){var b=a.args,c=a.event,d=a.method,e=a.sequenceId,f=a.tagOrTarget;if(this.X.includes(e))return B().error("amp-bind","One state action allowed per event."),T();this.X.push(e);this.Aa();if(b=b.__AMP_OBJECT_STRING__){this.J=Math.min(2E3,Math.max(1E3,this.J+500));this.oa.signal("FIRST_MUTATE");var g={};c&&c.detail&&(g.event=c.detail);switch(d){case "setState":return this.setStateWithExpression(b,g);case "pushState":return this.pushStateWithExpression(b,g);default:return Promise.reject(C().createError("Unrecognized method: %s.%s",
f,d))}}else B().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return T()};k.setStateWithExpression=function(a,b){var c=this;return zc(this,a,b).then(function(a){return Ac(c,a)})};k.setStateWithObject=function(a){return(a=Bc(a))?Ac(this,a):Promise.reject("Invalid state")};
function Ac(a,b){C().info("amp-bind","setState:",b);a.U=a.setState(b).then(function(){return Cc(a)}).then(function(b){b&&a.Z.replace(b)});return a.U}k.pushStateWithExpression=function(a,b){var c=this;C().info("amp-bind","pushState:",a);return zc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=F();Object.keys(a).forEach(function(a){d[a]=Bc(c.w[a])});return c.setState(a).then(function(){return Cc(c)}).then(function(a){c.Z.push(b,a)})})};
function Cc(a){var b=G({data:G({"amp-bind":a.w}),title:a.I.document.title});return a.V.isEmbedded()?a.V.isTrustedViewer().then(function(a){return a?b:null}):Promise.resolve(b)}k.rescan=function(a,b,c){var d=this,e=c=void 0===c?{}:c;return(e.fast?this.da.promise:this.M).then(function(){return d.Ea.timeoutPromise(e.timeout||2E3,Dc(d,a,b,e),"Timed out waiting for amp-bind to rescan.")})};
function Dc(a,b,c,d){C().info("amp-bind","rescan: ",b,c,d);return(d.fast?Ec(a,b,c):Fc(a,b,c)).then(function(){if(d.update)return xc(a).then(function(c){return yc(a,c,{constrain:b,evaluateOnly:"evaluate"===d.update})})})}
function Ec(a,b,c){var d=Gc(a,c),e=[],f=b.filter(function(a){return a.hasAttribute("i-amphtml-binding")});b.forEach(function(a){a=a.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,a)});var g=a.J-a.numberOfBindings();for(b=0;b<f.length&&!Hc(a,f[b],g-e.length,e);b++);d.then(function(b){C().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-b,a.numberOfBindings())});return 0<e.length?Ic(a,e):T()}
k.getState=function(a){a=a?jb(this.w,a):void 0;return x(a)||Array.isArray(a)?Bc(a):a};k.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.na.then(function(d){var e=d.querySelector("#"+String(c).replace(Wa,Xa));if(!e)throw Error("#"+c+" does not exist.");return eb(e).then(function(a){return a.getImpl(!0)}).then(function(a){return a.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
k.getStateValue=function(a){a=jb(this.w,a);return void 0===a||null===a?null:x(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function wc(a,b){var c=!ac(a.I.document);a.qa=new Gb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([Jc(a).then(function(){return a.da.resolve()}),Kc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(b){return Lc(a,b)})}).then(function(){var a=b.querySelectorAll("AMP-STATE"),c=v(a).map(function(a){return eb(a).then(function(){return a.getImpl(!1)}).then(function(a){return a.parseAndUpdate()})});return Promise.all(c)}).then(function(){a.V.sendMessage("bindReady",
void 0);if(q().development)return xc(a).then(function(b){return Mc(a,b)})})}k.numberOfBindings=function(){return this.G.reduce(function(a,b){return a+b.boundProperties.length},0)};k.Ja=function(a){this.J=a};k.Ha=function(){return this.Z};
k.Ba=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.ma.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&B().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};k.addOverridableKey=function(a){this.ma.push(a)};
function Jc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];cb(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Nc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Kc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(b){var c=a.J-a.numberOfBindings();return Oc(a,b,c).then(function(b){var c=b.bindings;b.limitExceeded&&C().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.J);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?Ic(a,b):0})}
function Ic(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.C[b];0<d.length&&Nc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function Gc(a,b){if(!b.length)return Promise.resolve(0);Wb(a.G,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.C){var e=a.C[d];Wb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.C[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Oc(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();Hc(a,b,c-e.length,e)&&(g=!0);if(uc.includes(b.nodeName))a:{for(b=f.currentNode;b;b=f.parentNode())if(b=f.nextSibling())break a;b=null}else b=f.nextNode();return!b||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var n=!1;if(f&&!f.didTimeout)for(;1<f.timeRemaining()&&
!n;)n=d();else for(f=0;250>f&&!n;f++)n=d();n?b({bindings:e,limitExceeded:g}):Mb(a.ampdoc,c)}Mb(a.ampdoc,c)})}function Hc(a,b,c,d){var e=!1,f=Pc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.G.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c.expressionString;d.push({tagName:g,property:c.property,expressionString:e});a.C[e]||(a.C[e]=[]);a.C[e].push(b)});return e}
function Pc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,l=a,n=d[e];var h=b;var r=h.tagName,m=n.name;if(2<m.length&&"["===m[0]&&"]"===m[m.length-1])g=m.substr(1,m.length-2);else if(Q(m,"data-amp-bind-")&&(g=m.substr(14),h.hasAttribute("["+g+"]"))){h=null;break a}if(g){if(l.qa.canBind(r,g)){h={property:g,expressionString:n.value};break a}g=B().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,r);Y(g,h)}h=null}h&&c.push(h)}return c}
function zc(a,b,c){return a.M.then(function(){Object.assign(c,a.w);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Nc(a,"amp-bind: Expression eval failed.");return b})}
function xc(a){return Z(a,"bind.evaluateBindings",[a.w]).then(function(b){var c=b.results,d=b.errors;Object.keys(d).forEach(function(b){var c=a.C[b];if(0<c.length){var e=d[b],l=B().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,e.message);l.stack=e.stack;Y(l,c[0])}});C().info("amp-bind","evaluation:",c);return c})}
function Mc(a,b){var c=void 0===c?!0:c;var d={};a.G.forEach(function(a){var e=a.element;a.boundProperties.forEach(function(a){var f=b[a.expressionString];if(void 0!==f){var g=a.property,h=tc[e.tagName];if(h&&h.includes(g))f=null;else{switch(g){case "text":g=e.textContent;f=String(f);h=g.trim()===f.trim();break;case "class":g=[];for(h=0;h<e.classList.length;h++){var r=e.classList[h];rc.test(r)||g.push(r)}r=[];Array.isArray(f)?r=f:"string"===typeof f?(h=f.trim(),0<h.length&&(r=h.split(" "))):(h=B().createError('%s: "%s" is not a valid result for [class].',
"amp-bind",f),Y(h,e));b:{h=g;var m=r;if(h.length!==m.length)h=!1;else{r=(Array.isArray(h)?h:v(h)).sort();m=(Array.isArray(m)?m:v(m)).sort();for(var t=0;t<h.length;t++)if(r[t]!==m[t]){h=!1;break b}h=!0}}break;default:g=e.getAttribute(g),h=!0===f?""===g:!1===f?null===g:"number"===typeof f?Number(g)===f:g===f}f=h?null:{expected:f,actual:g}}var E=f;if(E){f=e.tagName;g=a.property;a=a.expressionString;h=E.expected;var w=E.actual;d[f+"["+g+"]"+h+":"+w]=!0;c&&B().warn("amp-bind","Default value ("+w+") does not match first result ("+
(h+") for <"+f+" ["+g+']="')+(a+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(d)}function Qc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||lb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}
function yc(a,b,c){var d=[];a.G.forEach(function(e){if(!c.skipAmpState||"AMP-STATE"!==e.element.tagName)if(!c.constrain||c.constrain.some(function(a){return a.contains(e.element)})){var f=e.element,g=Qc(e.boundProperties,b);c.evaluateOnly||d.push(Rc(a,f,g))}});return Promise.all(d)}
function Rc(a,b,c){return 0===c.length?T():a.ka.mutateElement(b,function(){var d=F(),e,f;c.forEach(function(c){var g=c.boundProperty,h=c.newValue,l=g.property;a:{g=g.property;var m=b.tagName;switch(g){case "defaulttext":b.textContent=String(h);break;case "text":g=String(h);"TITLE"===m&&b.parentNode===a.I.document.head&&(a.I.document.title=g);"TEXTAREA"===m?b.value=g:b.textContent=g;break;case "class":g=[];for(m=0;m<b.classList.length;m++){var t=b.classList[m];rc.test(t)&&g.push(t)}Array.isArray(h)||
"string"===typeof h?b.setAttribute("class",g.concat(h).join(" ")):null===h?b.setAttribute("class",g.join(" ")):(g=B().createError('%s: "%s" is not a valid result for [class].',"amp-bind",h),Y(g,b));break;default:var E="INPUT"===m&&g in b,w=b.getAttribute(g);m=!1;if("boolean"===typeof h){if(E&&b[g]!==h&&(b[g]=h,m=!0),h&&""!==w?(b.setAttribute(g,""),m=!0):h||null===w||(b.removeAttribute(g),m=!0),m&&"OPTION"===b.tagName&&"selected"===g&&h&&O(a.h,"platform").isSafari()&&(t=bb(b,"select"))){var u=v(t.options).indexOf(b);
0<=u&&(t.selectedIndex=u)}}else if("object"===typeof h&&null!==h)m=!0;else if(h!==w)b:{w=String(h);try{t=b.tagName.toLowerCase();u=g.toLowerCase();var Ia="src"==u||"href"==u||"xlink:href"==u||"srcset"==u?mc(t,u,w):w;if(S(self.location)&&"a"===t&&"href"===u){var tb=b.getAttribute(u),ub="#"===Ia[0],vb=tb&&"#"===tb[0];ub&&!vb?(b.__AMP_ORIGINAL_TARGET_VALUE_||(b.__AMP_ORIGINAL_TARGET_VALUE_=b.getAttribute("target")),b.removeAttribute("target")):vb&&!ub&&b.setAttribute("target",b.__AMP_ORIGINAL_TARGET_VALUE_||
"_top")}E&&(b[u]=Ia);b.setAttribute(u,Ia);m=!0;break b}catch(Sc){m=B().createError('%s: "%s" is not a valid result for [%]',"amp-bind",w,g,Sc),Y(m,b)}m=!1}if(m){g={name:g,value:h};break a}}g=null}var Ja=g;Ja&&(d[Ja.name]=Ja.value,"width"==l?e="number"===typeof h&&isFinite(h)?Number(h):e:"height"==l&&(f="number"===typeof h&&isFinite(h)?Number(h):f));(h=sc[b.tagName])&&h[l]&&(l="OPTION"===b.tagName?bb(b,"SELECT"):b)&&(h=ob(a.I,"amp:form-value-change",null,{bubbles:!0}),l.dispatchEvent(h))});void 0===
e&&void 0===f||a.ka.forceChangeSize(b,f,e);if("function"===typeof b.mutatedAttributesCallback)try{b.mutatedAttributesCallback(d)}catch(l){var g=B().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(d),l);Y(g,b)}})}function Lc(a,b){b=b.target;var c=b.parentNode;c&&uc.includes(c.nodeName)||(C().info("amp-bind","dom_update:",b),Fc(a,[b],[b],"dom_update.end").then(function(){}))}
function Fc(a,b,c,d){var e=void 0===d?"rescan.slow":d,f=0;return Gc(a,c).then(function(c){f=c;return Kc(a,b)}).then(function(b){C().info("amp-bind","%s: delta=%s, total=%s",e,b-f,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.I;if(d.Worker){var e=J(d);wa(e,e,"amp-worker",Zb);b=$b(O(d,"amp-worker"),b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Nc(a,b,c){b=B().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}
function Bc(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){C().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
k.ya=function(a){if(a)if("string"==typeof a){var b=jb(this.w,a);B().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=B().assertElement(a),Tc(this,b)):B().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else B().info("amp-bind",this.w)};
function Tc(a,b){var c=Xb(a.G,function(a){return a.element==b});if(0>c)B().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.G[c].boundProperties;e.forEach(function(b){d.push(zc(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=F();e.forEach(function(c,d){b[c.property]=a[d]});B().info("amp-bind",b)})}}k.xa=function(a){zc(this,a,this.w).then(function(a){B().info("amp-bind",a)})};k.Ia=function(){return this.M};k.Ka=function(){return this.U};(function(a){a.registerServiceForDoc("bind",vc);a.registerElement("amp-state",pb);a.registerElement("amp-bind-macro",Ua)})(self.AMP);
})});

//# sourceMappingURL=MisterOperator-bind-0.1.js.map
