(self.AMP=self.AMP||[]).push({n:"amp-autocomplete",v:"2009252320001",f:(function(AMP,_){
'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m,r;function t(){return r?r:r=Promise.resolve(void 0)};function u(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ea(a){var b=Object.create(null);if(!a)return b;for(var c;c=da.exec(a);){var d=u(c[1],c[1]),e=c[2]?u(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var fa=Object.prototype.toString;function w(a){return Array.isArray(a)};function ha(a){var b=!1,c=null,d=a;return function(a){for(var e=[],g=0;g<arguments.length;++g)e[g-0]=arguments[g];b||(c=d.apply(self,e),b=!0,d=null);return c}};var x=self.AMP_CONFIG||{},ia=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ja(a){if(!self.document||!self.document.head||self.location&&ia.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ka={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||ja("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ia,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:x.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:x.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl||ja("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var y=self.__AMP_LOG;function z(){if(!y.user)throw Error("failed to call initLogConstructor");return y.user}function la(){if(y.dev)return y.dev;throw Error("failed to call initLogConstructor");}function ma(){}function A(a,b,c,d,e){z().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var B=Object.prototype.hasOwnProperty;function C(a){return a||{}}function D(a,b){if(B.call(a,b))return a[b]};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function na(a,b){var c;"number"!==typeof c&&(c=0);return c+b.length>a.length?!1:-1!==a.indexOf(b,c)};function oa(a){var b=a.element;this.W=b;this.G=this.W.getAttribute("inline");A(""!==this.G,'Empty value for the "inline" attr is unsupported, %s. %s',"amp-autocomplete",b);A(""!==this.G,"AutocompleteBindingInline does not support an empty value in the constructor.");this.C=null;var c=this.G.replace(/([()[{*+.$^\\|?])/g,"\\$1");this.ca=new RegExp("(("+c+"|^"+c+")(\\w+)?)","gm")}l=oa.prototype;
l.shouldAutocomplete=function(a){var b;if(b=this.ca){for(var c=a.value,d=a.selectionStart,e,f;null!==(e=b.exec(c))&&!(e[0].length+D(e,"index")>d);)f=e;b=!f||f[0].length+D(f,"index")<d?null:f}else b=null;this.C=b;return!!b};l.getUserInputForUpdate=function(){return this.C&&this.C[0]?this.C[0].slice(this.G.length):""};
l.getUserInputForUpdateWithSelection=function(a,b,c){if(!this.C)return b.value;var d=b.selectionStart,e=Number(D(this.C,"index")),f=c.length;d>=e+f&&(d-=f);try{b.focus()}catch(k){}d=d+a.length+1;b.setSelectionRange(d,d);this.C=null;b=b.value;var g=b.slice(0,e+this.G.length),h=b.slice(e+this.G.length+f);return g+a+" "+h};l.resetInputOnWrapAround=function(){};l.shouldSuggestFirst=function(){return this.W.hasAttribute("suggest-first")};l.shouldShowOnFocus=function(){return!1};
l.displayActiveItemInInput=function(){};l.removeSelectionHighlighting=function(){};l.shouldPreventDefaultOnEnter=function(a){return a};function pa(a){a=a.element;this.A=a.hasAttribute("suggest-first");var b=a.getAttribute("filter");this.A&&"prefix"!==b&&(this.A=!1,z().warn("AMP-AUTOCOMPLETE",'"suggest-first" expected "filter" type "prefix".'));this.ea=a.hasAttribute("submit-on-enter")}l=pa.prototype;l.shouldAutocomplete=function(){return!0};l.getUserInputForUpdate=function(a){return a.value||""};l.getUserInputForUpdateWithSelection=function(a){return a};l.resetInputOnWrapAround=function(a,b){b.value=a};l.shouldSuggestFirst=function(){return this.A};
l.shouldShowOnFocus=function(){return!0};l.displayActiveItemInInput=function(a,b,c){a.value=b;this.A&&a.setSelectionRange(c.length,b.length)};l.removeSelectionHighlighting=function(a){var b=a.value.length;a.setSelectionRange(b,b)};l.shouldPreventDefaultOnEnter=function(){return!this.ea};function qa(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;if(d.__AMP__EXPERIMENT_TOGGLES)var f=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);f=d.__AMP__EXPERIMENT_TOGGLES;if(d.AMP_CONFIG)for(var g in d.AMP_CONFIG){var h=d.AMP_CONFIG[g];"number"===typeof h&&0<=h&&1>=h&&(f[g]=Math.random()<h)}if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(g=d.AMP_CONFIG["allow-doc-opt-in"],
h=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){h=h.getAttribute("content").split(",");for(var k=0;k<h.length;k++)-1!=g.indexOf(h[k])&&(f[h[k]]=!0)}Object.assign(f,ra(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&0<d.AMP_CONFIG["allow-url-opt-in"].length)for(g=d.AMP_CONFIG["allow-url-opt-in"],h=ea(d.location.originalHash||d.location.hash),k=0;k<g.length;k++){var v=h["e-"+g[k]];"1"==v&&(f[g[k]]=!0);"0"==v&&(f[g[k]]=!1)}}f=!!f["ampdoc-fie"];e&&!f?b=E(c,
b)?F(c,b):null:(a=G(a),a=sa(a),b=E(a,b)?F(a,b):null);return b}function H(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return F(a,b)}function ta(a,b){var c=G(a);c=sa(c);return F(c,b)}function G(a){return a.nodeType?H((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function sa(a){a=G(a);return a.isSingleDoc()?a.win:a}
function F(a,b){E(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function E(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};function I(){this.aa=100;this.O=this.U=0;this.K=Object.create(null)}I.prototype.has=function(a){return!!this.K[a]};I.prototype.get=function(a){var b=this.K[a];if(b)return b.access=++this.O,b.payload};I.prototype.put=function(a,b){this.has(a)||this.U++;this.K[a]={payload:b,access:this.O};if(!(this.U<=this.aa)){la().warn("lru-cache","Trimming LRU cache");a=this.K;var c=this.O+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.U--)}};var ua=C({c:!0,v:!0,a:!0,ad:!0}),J,va,wa=/[?&]amp_js[^&]*/,xa=/[?&]amp_gsa[^&]*/,ya=/[?&]amp_r[^&]*/,za=/[?&]amp_kit[^&]*/,Aa=/[?&]usqp[^&]*/;
function K(a){J||(J=self.document.createElement("a"),va=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new I));var b=va,c=J;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function Ba(a,b,c){b=encodeURIComponent(b)+"="+encodeURIComponent(c);b&&(a=a.split("#",2),c=a[0].split("?",2),b=c[0]+(c[1]?"?"+c[1]+"&"+b:"?"+b),a=b+=a[1]?"#"+a[1]:"");return a}
function Ea(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(w(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function Fa(a,b){var c=void 0===c?"source":c;A(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=K(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);A(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)};function ra(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){la().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function Ga(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ha(a){return!!a&&"function"==typeof a.getFormData};var Ia=["GET","POST"],Ja=[w,function(a){return"[object Object]"===fa.call(a)}];function Ka(a){a=a||{};var b=a.method;void 0===b?b="GET":(b=b.toUpperCase(),Ia.includes(b));a.method=b;a.headers=a.headers||C({});a.headers.Accept="application/json";return a}
function La(a){var b=Ka(a);"POST"!=b.method||Ha(b.body)||(ma(Ja.some(function(a){return a(b.body)})),b.headers["Content-Type"]=b.headers["Content-Type"]||"text/plain;charset=utf-8",b.body="application/x-www-form-urlencoded"===b.headers["Content-Type"]?Ea(b.body):JSON.stringify(b.body))};function L(a,b){this.N=a;this.D=b;this.da="amp-autocomplete"}L.prototype.isEnabled=function(){var a=this.N.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.N.hasCapability("viewerRenderTemplate"):!1};L.prototype.assertTrustedViewer=function(a){return this.N.isTrustedViewer().then(function(b){A(b,"Refused to attempt SSR in untrusted viewer: ",a)})};
L.prototype.ssr=function(a,b,c,d){var e=this;c=void 0===c?null:c;d=void 0===d?{}:d;var f=c,g=d,h;f||(h=this.D.maybeFindTemplate(a));return this.assertTrustedViewer(a).then(function(){return e.N.sendMessageAwaitResponse("viewerRenderTemplate",Ma(e,b,h,f,g))})};
L.prototype.applySsrOrCsrTemplate=function(a,b){var c=this;if(this.isEnabled()){A("string"===typeof b.html,"Server side html response must be defined");var d=this.assertTrustedViewer(a).then(function(){return c.D.findAndSetHtmlForTemplate(a,b.html)})}else d=w(b)?this.D.findAndRenderTemplateArray(a,b):this.D.findAndRenderTemplate(a,b);return d};
function Ma(a,b,c,d,e){var f=e=void 0===e?{}:e,g=C({type:a.da}),h=d&&d.successTemplate?d.successTemplate:c;h&&(g.successTemplate={type:"amp-mustache",payload:h.innerHTML});var k=d&&d.errorTemplate?d.errorTemplate:null;k&&(g.errorTemplate={type:"amp-mustache",payload:k.innerHTML});f&&Object.assign(g,f);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if(Ha(c.body)){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:g})};function M(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function Na(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function Oa(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Fa(b.getAttribute("src"),b);var h=H(a.win,"batched-xhr");return Pa(b,e,f).then(function(a){return h.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return H(a.win,"xhr").xssiJson(b,g)}).then(function(a){if(null==a)throw Error("Response is undefined.");return M(a,d||".")}).catch(function(a){throw z().createError("failed fetching JSON data",
a);})}
function Pa(a,b,c){var d=a.getAttribute("src"),e=qa(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectDisallowedVarsSync(a);if(0<f.length)throw z().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(f.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));c&&
(h.cache="reload");return{xhrUrl:d,fetchOpt:h}})};function Qa(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function Ra(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};function Sa(a,b){return 0<a&&0<b?a%b:(a%b+b)%b};function Ta(a,b){var c=b.length,d=a.length;if(d>c)return!1;if(d===c&&a===b)return!0;var e=0,f=0;a:for(;e<d;e++){for(var g=a.charCodeAt(e);f<c;)if(b.charCodeAt(f++)===g)continue a;return!1}return!0};var Ua={SUBSTRING:"substring",PREFIX:"prefix",TOKEN_PREFIX:"token-prefix",FUZZY:"fuzzy",CUSTOM:"custom",NONE:"none"};
function N(a){var b=AMP.BaseElement.call(this,a)||this;b.w=null;b.o=null;b.h=null;b.j="";b.B="";b.Z=1;b.J=null;b.A=!1;b.R=!1;b.X=!1;b.M="";b.L="";b.F=-1;b.l=null;b.ba=a.id?a.id:Math.floor(100*Math.random());b.m=null;b.H=!1;b.T=null;b.D=H(b.win,"templates");b.S=!1;b.getSsrTemplateHelper=ha(function(){return new L(ta(b.element,"viewer"),b.D)});b.I=!1;b.V=null;b.$=null;b.Y=!1;b.P=a.id?a.id:Math.floor(100*Math.random())+"_AMP_content_";return b}var O=AMP.BaseElement;N.prototype=aa(O.prototype);
N.prototype.constructor=N;if(q)q(N,O);else for(var P in O)if("prototype"!=P)if(Object.defineProperties){var Va=Object.getOwnPropertyDescriptor(O,P);Va&&Object.defineProperty(N,P,Va)}else N[P]=O[P];N.fa=O.prototype;
N.prototype.buildCallback=function(){var a=this.element.ownerDocument,b=a&&Ra(a);A(!b||a.documentElement.hasAttribute("data-amp-autocomplete-opt-in"),"<amp-autocomplete> is not currently available in AMP4Email.");this.V=qa(this.element,"action");this.$=ta(this.element,"viewport");a=this.element.querySelectorAll("input,textarea");A(1==a.length,"%s should contain exactly one <input> or <textarea> descendant %s","amp-autocomplete",this.element);this.h=a[0];var c=this.h.getAttribute("type");A(!this.h.hasAttribute("type")||
"text"===c||"search"===c,'%s requires the "type" attribute to be "text" or "search" if present on <input>. %s',"amp-autocomplete",this.element);this.w=this.element.hasAttribute("inline")?new oa(this):new pa(this);this.L=this.element.getAttribute("query");this.M=this.element.getAttribute("src");var d=this.element.querySelector('script[type="application/json"]');d?this.o=Wa(this,d):this.element.hasAttribute("src")||z().warn("amp-autocomplete",'Expected a <script type="application/json"> child or a URL specified in "src".');
this.h.setAttribute("dir","auto");this.h.setAttribute("aria-autocomplete","both");this.h.setAttribute("role","textbox");this.h.setAttribute("aria-controls",this.P);"INPUT"===this.h.tagName&&(this.element.setAttribute("role","combobox"),this.h.setAttribute("aria-multiline","false"));this.element.setAttribute("aria-haspopup","listbox");this.element.setAttribute("aria-expanded","false");this.element.setAttribute("aria-owns",this.P);(a=this.h.form||null)&&a.hasAttribute("autocomplete")&&(this.T=a.getAttribute("autocomplete"));
this.I=this.getSsrTemplateHelper().isEnabled();this.S=this.D.hasTemplate(this.element,"template, script[template]");this.I&&(A(this.M,'%s requires data to be provided via "src" attribute for server-side rendering. %s',"amp-autocomplete",this.element),A(this.S,'amp-autocomplete should provide a <template> or <script type="plain/text"> element.'),A(!this.element.hasAttribute("filter"),"amp-autocomplete does not support client-side filter when server-side render is required."));this.B=this.element.getAttribute("filter")||
"none";a:{for(e in Ua)if(Ua[e]===this.B){var e=!0;break a}e=!1}A(e,"Unexpected filter: %s. %s",this.B,this.element);this.Z=this.element.hasAttribute("min-characters")?parseInt(this.element.getAttribute("min-characters"),10):1;this.element.hasAttribute("max-entries")&&z().warn("amp-autocomplete",'"max-items" attribute is preferred to "max-entries"');var f=this.element.getAttribute("max-items")||this.element.getAttribute("max-entries");this.J=f?parseInt(f,10):null;this.A=this.w.shouldSuggestFirst();
this.X=this.element.hasAttribute("highlight-user-entry");e=this.element.ownerDocument.createElement("div");e.classList.add("i-amphtml-autocomplete-results");Xa(this)&&e.classList.add("i-amphtml-autocomplete-results-up");e.setAttribute("role","listbox");e.setAttribute("id",this.P);Ga(e,!1);this.m=e;this.element.appendChild(this.m);return t()};
function Wa(a,b){b=Na(b.textContent,function(a){throw a;});var c=a.element.getAttribute("items")||"items",d=M(b,c);return d?z().assertArray(d):(z().warn("amp-autocomplete",'Expected key "%s" in data but found nothing. Rendering empty results.',c),[])}
function Q(a){var b=a.getAmpDoc(),c=a.element.getAttribute("items")||"items";Ya(a);return a.I?Pa(a.element,2,!1).then(function(b){var d=a.win,f=b.xhrUrl;if(!1!==b.fetchOpt.ampCors){var g=K(f);g=ea(g.search);A(!("__amp_source_origin"in g),"Source origin is not allowed in %s",f);d=d.location.href;"string"==typeof d&&(d=K(d));g=d;"string"==typeof g&&(g=K(g));if(ka.cdnProxyRegex.test(g.origin)){g=d.pathname.split("/");A(ua[g[1]],"Unknown path prefix in url %s",d.href);var h=g[2],k="s"==h?"https://"+decodeURIComponent(g[3]):
"http://"+decodeURIComponent(h);A(0<k.indexOf("."),"Expected a . in origin %s",k);g.splice(1,"s"==h?3:2);g=k+g.join("/");h=(h=d.search)&&"?"!=h?(h=h.replace(wa,"").replace(xa,"").replace(ya,"").replace(za,"").replace(Aa,"").replace(/^[?&]/,""))?"?"+h:"":"";d=g+h+(d.hash||"")}else d=d.href;d=K(d).origin;f=Ba(f,"__amp_source_origin",d)}b.xhrUrl=f;d=b.xhrUrl;f=(f=b.fetchOpt)||{};g=a.win;g=g.origin||K(g.location.href).origin;d=K(d).origin;g==d&&(f.headers=f.headers||{},f.headers["AMP-Same-Origin"]="true");
b.fetchOpt=f;La(b.fetchOpt);f=C({ampAutocompleteAttributes:{items:c,maxItems:a.J}});return a.getSsrTemplateHelper().ssr(a.element,b,null,f)}):Oa(b,a.element,{expr:c,urlReplacement:2}).catch(function(){z().warn("amp-autocomplete",'Expected key "%s" in data but found nothing. Rendering empty results.',c);return[]})}function Ya(a){if(a.L){var b=a.j;b=Ba(a.M,a.L,void 0===b?"":b);a.element.setAttribute("src",b)}}
N.prototype.layoutCallback=function(){var a=this;this.h.setAttribute("autocomplete","off");this.h.addEventListener("touchstart",function(){Za(a)},{passive:!0});this.h.addEventListener("input",function(){$a(a)});this.h.addEventListener("keydown",function(b){ab(a,b)});this.h.addEventListener("focus",function(){Za(a).then(function(){var b=a.w.shouldShowOnFocus();bb(a,b)})});this.h.addEventListener("blur",function(){bb(a,!1)});this.m.addEventListener("mousedown",function(b){cb(a,b)});return R(this,this.o,
this.j)};N.prototype.mutatedAttributesCallback=function(a){var b=this,c=a.src;if(void 0===c||null===c)return t();if("string"===typeof c)return this.M=c,Q(this).then(function(a){b.o=a||[];R(b,b.o,b.j)},function(a){db(b,a)});if("object"===typeof c)return this.o=c.items||[],R(this,this.o,this.j);z().error("amp-autocomplete",'Unexpected "src" type: '+c)};
function eb(a,b,c){var d=void 0===c?"":c;c=a.element.ownerDocument.createElement("div");c.classList.add("i-amphtml-autocomplete-item");c.setAttribute("role","option");c.setAttribute("data-value",b);c.setAttribute("dir","auto");c.textContent=b;var e=c.childNodes[0],f=b.toLocaleLowerCase(),g=d.toLocaleLowerCase();if(a.X&&d&&d.length<=b.length&&na(f,g)){var h=f.indexOf(g),k=a.element.ownerDocument.createElement("span");k.classList.add("autocomplete-partial");k.appendChild(a.element.ownerDocument.createTextNode(b.slice(h,
h+d.length)));var v=e.splitText(h);v.splitText(d.length);c.replaceChild(k,v)}return c}function $a(a){a.w.shouldAutocomplete(a.h)?fb(a):a.mutateElement(function(){S(a)})}function fb(a){var b=0===a.j.length&&1===a.h.value.length;a.j=a.w.getUserInputForUpdate(a.h);(a.I||a.L?Q(a):Promise.resolve(a.o)).then(function(c){a.o=c;return a.mutateElement(function(){R(a,a.o,a.j).then(function(){T(a,!0);a.A&&(a.R&&!b||U(a,1),a.R=!1)})})})}
function cb(a,b){var c=V(a,gb(a,b.target));a.mutateElement(function(){W(a,c)})}function R(a,b,c){var d=c=void 0===c?"":c;S(a);d.length<a.Z||!b?a=t():a.I?a=B.call(b,"html")?hb(a,b,a.m,d):t():b.length?(b=ib(a,b,d),a=hb(a,b,a.m,d)):a=t();return a}
function hb(a,b,c,d){var e=t();X(a);a.S?e=a.getSsrTemplateHelper().applySsrOrCsrTemplate(a.element,b).then(function(a){(w(a)?a:[a]).forEach(function(a){a.hasAttribute("data-disabled")?a.setAttribute("aria-disabled","true"):a.hasAttribute("data-value")||z().warn("amp-autocomplete",'Expected a "data-value" or "data-disabled" attribute on the rendered template item. %s',a);a.classList.add("i-amphtml-autocomplete-item");a.setAttribute("role","option");c.appendChild(a)})}):b.forEach(function(b){A("string"===
typeof b,"%s data must provide template for non-string items. %s","amp-autocomplete",a.element);c.appendChild(eb(a,b,d))});return e}
function ib(a,b,c){if("none"===a.B)return jb(a,b);c=c.toLocaleLowerCase();var d=a.element.getAttribute("filter-value")||"value";b=b.filter(function(b){"object"===typeof b&&(b=M(b,d));A("string"===typeof b,'%s data property "%s" must map to string type. %s',"amp-autocomplete",d,a.element);b=b.toLocaleLowerCase();switch(a.B){case "substring":return na(b,c);case "prefix":return c.length>b.length?!1:0==b.lastIndexOf(c,0);case "token-prefix":return kb(b,c);case "fuzzy":return Ta(c,b);case "custom":throw Error("Filter not yet supported: %s",
a.B,a.element);default:throw Error("Unexpected filter: %s",a.B,a.element);}});return jb(a,b)}function kb(a,b){if(""===b)return!0;var c=lb(a),d=lb(b),e=mb(c),f=d[d.length-1];d.splice(d.length-1,1);a=!0;for(b=0;b<d.length;b++){var g=d[b];if(""!==g){if(!B.call(e,g)){a=!1;break}var h=Number(D(e,g));1<h?e[g]=h-1:delete e[g]}}var k=Object.keys(e);return a&&(""===f||k.some(function(a){return f.length>a.length?!1:0==a.lastIndexOf(f,0)}))}
function lb(a){a=a.replace(/[\.]+/g,"");return a.split(/[`~(){}_|+\-;:'",\[\]\\\/ ]+/g)}function mb(a){var b=Object.create(null);a.forEach(function(a){var c=B.call(b,a)?D(b,a)+1:1;b[a]=c});return b}function jb(a,b){a.J&&a.J<b.length&&(b=b.slice(0,a.J));return b}function T(a,b){a.h.setAttribute("aria-expanded",b);Ga(a.m,b)}
function bb(a,b){var c=a.h.form||null;c&&(b?c.setAttribute("autocomplete","off"):a.T?c.setAttribute("autocomplete",a.T):c.removeAttribute("autocomplete"));var d=!1;a.measureMutateElement(function(){d=Xa(a)},function(){b||(a.j=a.h.value,R(a,a.o,a.j),X(a));a.m.classList.toggle("i-amphtml-autocomplete-results-up",d);T(a,b)})}function Za(a){if(a.Y||!a.element.hasAttribute("src"))return t();a.Y=!0;return Q(a).then(function(b){a.o=b;R(a,a.o)},function(b){db(a,b)})}
function Xa(a){var b=a.$.getHeight()||0;return a.h.getBoundingClientRect().top>b/2}function Y(a){return!a.m.hasAttribute("hidden")&&0<a.m.children.length}function gb(a,b){return null===b?null:b.classList.contains("i-amphtml-autocomplete-item")?b:gb(a,b.parentElement)}function V(a,b){if(null===b||b.hasAttribute("data-disabled"))return null;b=b.getAttribute("data-value")||b.textContent||"";a.h.value=a.w.getUserInputForUpdateWithSelection(b,a.h,a.j);a.j=a.w.getUserInputForUpdate(a.h);return b}
function W(a,b){if(null!==b){var c=Qa(a.win,"amp-autocomplete.select",{value:b});a.V.trigger(a.element,"select",c,3);b=Qa(a.win,"change",{value:b},{bubbles:!0});a.h.dispatchEvent(b);S(a);T(a,!1)}}
function U(a,b){if(0===b||!Y(a)||a.H)t();else{var c=-1===a.F&&0>b?b:a.F+b,d=nb(a);if(0===d.length)t();else{var e=Sa(c,d.length),f=d[e];c=f.getAttribute("data-value");a.w.displayActiveItemInInput(a.h,c,a.j);var g,h;a.measureMutateElement(function(){var c=f.offsetTop,d=f.offsetHeight,e=a.m,Ca=e.scrollTop,Da=e.offsetHeight;g=Ca>c||Ca+Da<c+d;h=0<b?c+d-Da:c},function(){g&&(a.m.scrollTop=h);X(a);f.classList.add("i-amphtml-autocomplete-item-active");f.setAttribute("aria-selected","true");var b=f.getAttribute("id");
b||(b=a.ba+"_AMP_content_"+e,f.setAttribute("id",b));a.h.setAttribute("aria-activedescendant",b);a.F=e;a.l=f;try{a.l.focus()}catch(v){}})}}}function nb(a){return a.m.querySelectorAll(".i-amphtml-autocomplete-item:not([data-disabled])")}function Z(a){a.w.resetInputOnWrapAround(a.j,a.h);X(a)}
function X(a){a.l&&(a.l.classList.toggle("i-amphtml-autocomplete-item-active",!1),a.l.removeAttribute("aria-selected"),"autocomplete-selected"===a.l.getAttribute("id")&&a.l.removeAttribute("id"),a.h.removeAttribute("aria-activedescendent"),a.l=null,a.F=-1)}function S(a){a.H=!1;for(a=a.m;a.firstChild;)a.removeChild(a.firstChild)}
function ab(a,b){switch(b.key){case "ArrowDown":b.preventDefault();if(Y(a)){if(a.F===nb(a).length-1){Z(a);t();break}U(a,1);break}a.mutateElement(function(){R(a,a.o,a.j);T(a,!0)});break;case "ArrowUp":b.preventDefault();if(0===a.F){Z(a);t();break}U(a,-1);break;case "Enter":var c=a.w.shouldPreventDefaultOnEnter(!!a.l);Y(a)&&c&&b.preventDefault();a.w.removeSelectionHighlighting(a.h);if(Y(a)&&a.l){var d=V(a,a.l);a.mutateElement(function(){W(a,d);X(a)});break}a.mutateElement(function(){T(a,!1)});break;
case "Escape":a.mutateElement(function(){a.H||(b.preventDefault(),Z(a),T(a,!1))});break;case "Tab":if(Y(a)&&a.l){b.preventDefault();var e=V(a,a.l);a.mutateElement(function(){W(a,e)});break}t();break;case "Backspace":a.R=a.A;t();break;default:t()}}function db(a,b){if(!a.H)if(S(a),a.getFallback())a.H=!0,a.toggleFallback(!0);else throw b;}N.prototype.isLayoutSupported=function(a){return"container"==a};(function(a){a.registerElement("amp-autocomplete",N,"amp-autocomplete,amp-autocomplete>input,amp-autocomplete>textarea{font-family:sans-serif}amp-autocomplete>input,amp-autocomplete>textarea{border-radius:4px;box-sizing:border-box}.i-amphtml-autocomplete-results{position:absolute;top:100%;width:calc(100% + 1rem);min-width:calc(2em + 2rem);max-height:40vh;margin-top:.5rem;margin-left:-.5rem;border-radius:4px;overflow-y:auto;overflow-x:hidden;background-color:#fff;box-shadow:0px 2px 4px 0px rgba(0,0,0,0.5);z-index:10}.i-amphtml-autocomplete-results-up{top:auto;bottom:100%;margin-bottom:.5rem}.i-amphtml-autocomplete-item{position:relative;padding:.5rem 1rem;cursor:pointer}.i-amphtml-autocomplete-item:first-child{border-radius:4px 4px 0px 0px}.i-amphtml-autocomplete-item:nth-last-child(2){border-radius:0px 0px 4px 4px}.i-amphtml-autocomplete-item-active:not([data-disabled]),.i-amphtml-autocomplete-item:hover:not([data-disabled]){background-color:rgba(0,0,0,0.15)}.i-amphtml-autocomplete-item[data-disabled]{color:rgba(0,0,0,0.33)}\n/*# sourceURL=/extensions/amp-autocomplete/0.1/amp-autocomplete.css*/")})(self.AMP);
})});

//# sourceMappingURL=MisterOperator-autocomplete-0.1.js.map
