(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"2009252320001",f:(function(AMP,_){
'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var p;a:{var ca={a:!0},q={};try{q.__proto__=ca;p=q.a;break a}catch(a){}p=!1}m=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m,u;function v(){return u?u:u=Promise.resolve(void 0)};function w(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var y=self.AMP_CONFIG||{},z=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function A(a){if(!self.document||!self.document.head||self.location&&z.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ea={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||A("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:z,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||A("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var B=self.__AMP_LOG;function C(){if(!B.user)throw Error("failed to call initLogConstructor");return B.user}function D(){if(B.dev)return B.dev;throw Error("failed to call initLogConstructor");}function E(a,b,c,d,e){C().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function F(a){return a||{}};var G;function fa(a,b){var c=a,d=b;var e=function(a){try{return d(a)}catch(k){throw self.__AMP_REPORT_ERROR(k),k;}};var f=ha();c.addEventListener("message",e,f?void 0:!1);return function(){c&&c.removeEventListener("message",e,f?void 0:!1);e=c=d=null}}function ha(){if(void 0!==G)return G;G=!1;try{var a={get capture(){G=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return G};function ia(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ja(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function H(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function ka(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function la(a){return a.closest?a.closest(".i-amphtml-overlay"):ka(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-overlay"):!1})};function ma(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function na(a){if(!oa(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return D().error("MESSAGING","Failed to parse message: "+a,c),null}}function oa(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function pa(a,b){return fa(a,b)};function I(){this.T=100;this.I=this.M=0;this.w=Object.create(null)}I.prototype.has=function(a){return!!this.w[a]};I.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.I,b.payload};I.prototype.put=function(a,b){this.has(a)||this.M++;this.w[a]={payload:b,access:this.I};if(!(this.M<=this.T)){D().warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.I+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.M--)}};F({c:!0,v:!0,a:!0,ad:!0});var J,qa;
function ra(a){J||(J=self.document.createElement("a"),qa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new I));var b=qa,c=J;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a};function sa(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)};var K,ta="Webkit webkit Moz moz ms O o".split(" ");function ua(a,b){var c=a.style;if(H("zIndex","--"))c="zIndex";else{K||(K=Object.create(null));var d=K.zIndex;if(!d){d="zIndex";if(void 0===c.zIndex){var e;b:{for(e=0;e<ta.length;e++){var f=ta[e]+"ZIndex";if(void 0!==c[f]){e=f;break b}}e=""}void 0!==c[e]&&(d=e)}K.zIndex=d}c=d}c&&(H(c,"--")?a.style.setProperty(c,b):a.style[c]=b)};function va(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function wa(a,b,c){var d=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=va(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===b){var f=e;break}}f||(f={frame:b,events:Object.create(null)},a.push(f));return f.events}
function xa(a){for(var b=F({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function ya(a){a.listeningFors||a.addEventListener("message",function(b){if(b.data){var c=za(b.data);if(c&&c.sentinel){var d=b.source;var e=va(a,c.sentinel);if(e){for(var f,g=0;g<e.length;g++){var k=e[g],n=k.frame.contentWindow;if(n){var h;if(!(h=d==n))b:{for(h=d;h&&h!=h.parent;h=h.parent)if(h==n){h=!0;break b}h=!1}if(h){f=k;break}}else setTimeout(xa,0,e)}d=f?f.events:null}else d=e;var t=d;if(t){var x=t[c.type];if(x)for(x=x.slice(),d=0;d<x.length;d++)(0,x[d])(c,b.source,b.origin,b)}}}})}
function L(a,b,c,d,e,f){function g(b,d,g,h){if("amp"==b.sentinel){if(d!=a.contentWindow)return;var k="null"==g&&f;if(n!=g&&!k)return}if(e||d==a.contentWindow)"unlisten"==b.sentinel?t():c(b,d,g,h)}var k=a.ownerDocument.defaultView;ya(k);d=wa(k,a,d);var n=ra(a.src).origin,h=d[b]||(d[b]=[]),t;h.push(g);return t=function(){if(g){var a=h.indexOf(g);-1<a&&h.splice(a,1);c=h=g=null}}}
function Aa(a,b,c,d,e){if(a.contentWindow)for(d.type=c,d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp",a=d,e&&(a="amp-"+JSON.stringify(d)),d=0;d<b.length;d++)e=b[d],e.win.postMessage(a,e.origin)}function za(a){"string"==typeof a&&(a="{"==a.charAt(0)?ma(a,function(a){D().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:oa(a)?na(a):null);return a}
function M(a,b){var c=this;this.h=a;this.K=!1;this.m=[];this.U=L(this.h,"send-intersections",function(a,e,f){c.m.some(function(a){return a.win==e})||c.m.push({win:e,origin:f});b(a,e,f)},this.K,this.K)}M.prototype.send=function(a,b){sa(this.m,function(a){return!a.win.parent});Aa(this.h,this.m,a,b,this.K)};M.prototype.destroy=function(){this.U();this.m.length=0};var N=[[300,250],[320,50],[300,50],[320,100]];function Ba(a,b,c){if(!(0==b&&0==c||0==a.width&&0==a.height)){b=a.left+b;c=a.top+c;var d=a.width;a=a.height;a={left:b,top:c,width:d,height:a,bottom:c+a,right:b+d,x:b,y:c}}return a};var Ca=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1];Date.now();function Da(a,b){var c=this;this.S=a;this.C=null;this.N=new M(b,function(){c.C.observe(c.S.element)});this.C=new IntersectionObserver(function(a){c.N.send("intersection",F({changes:a.map(Ea)}))},{threshold:Ca})}Da.prototype.destroy=function(){this.C.disconnect();this.C=null;this.N.destroy();this.N=null};
function Ea(a){return{time:a.time,rootBounds:a.rootBounds,boundingClientRect:a.boundingClientRect,intersectionRect:a.intersectionRect,intersectionRatio:a.intersectionRatio}};function O(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d,f=Fa(d,"ampdoc-fie");e&&!f?b=P(c,b)?Q(c,b):null:(a=R(a),a=S(a),b=P(a,b)?Q(a,b):null);return b}function T(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Q(a,b)}function R(a){return a.nodeType?T((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function S(a){a=R(a);return a.isSingleDoc()?a.win:a}
function Q(a,b){P(a,b);a=U(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ga(a){var b=U(a).consentPolicyManager;if(b){if(b.promise)return b.promise;Q(a,"consentPolicyManager");return b.promise=Promise.resolve(b.obj)}return null}function U(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function P(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Ha(){var a=new ia,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Fa(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ia(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=da.exec(e);)f=w(g[1],g[1]),g=g[2]?w(g[2].replace(/\+/g," "),g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}return!!c[b]}
function Ia(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){D().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function V(a){var b=Ga(S(a));if(b)return b;var c=R(a);return c.waitForBodyOpen().then(function(){var a=c.win;var b=c.win.document.head;if(b){var f={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var g=0;g<b.length;g++){var k=b[g];k=k.getAttribute("custom-element")||k.getAttribute("custom-template");f[k]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-consent")?T(a,"extensions").waitForExtension(a,"amp-consent"):v()}).then(function(){var b=c.win;if(b.__AMP_EXTENDED_ELEMENTS&&
b.__AMP_EXTENDED_ELEMENTS["amp-consent"]){b=S(a);var e=Ga(b);e?b=e:(b=U(b),b.consentPolicyManager=Ha(),b=b.consentPolicyManager.promise)}else b=null;return b})};function Ja(a,b){var c=b=void 0===b?"default":b;return V(a).then(function(a){return a?a.whenPolicyResolved(c):null})}function Ka(a,b){return V(a).then(function(a){return a?a.getConsentStringInfo(b):null})}function La(a,b){return V(a).then(function(a){return a?a.getConsentMetadataInfo(b):null})};var Ma={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};var Na="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling tabindex title".split(" "),Oa=0;function W(a){a=AMP.BaseElement.call(this,a)||this;a.G=null;a.D=!1;a.L=!1;a.o=!1;a.R=!1;a.J=null;a.h=null;a.F=!1;a.B=null;a.l="";a.H=null;a.iframeSrc=null;a.A=null;a.j=null;a.P=!1;return a}var X=AMP.BaseElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;
if(r)r(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Pa=Object.getOwnPropertyDescriptor(X,Y);Pa&&Object.defineProperty(W,Y,Pa)}else W[Y]=X[Y];W.W=X.prototype;l=W.prototype;l.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
function Qa(a,b,c){var d=window.location.href,e=c=void 0===c?"":c;a=a.element;var f=O(a,"url"),g=f.parse(b),k=g.hostname,n=g.protocol;g=g.origin;E(f.isSecure(b)||"data:"==n,"Invalid <amp-iframe> src. Must start with https://. Found %s",a);var h=f.parse(d);E(!/\sallow-same-origin\s/i.test(" "+e+" ")||g!=h.origin&&"data:"!=n,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",
a);E(!(ja(k,"."+ea.thirdPartyFrameHost)||ja(k,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",b);return b}
function Ra(a){var b=a.element.getLayoutBox(),c=Math.min(600,.75*a.getViewport().getSize().height);E(b.top>=c,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",a.element,b.top,c)}
function Sa(a,b){if(b){a=O(a.element,"url").parse(b);var c=a.hash;"data:"==a.protocol||c&&"#"!=c||(a=b.indexOf("#"),b=(-1==a?b:b.substring(0,a))+"#amp=1");return b}}
l.firstAttachedCallback=function(){this.l=this.element.getAttribute("sandbox");var a;if(!(a=Sa(this,this.element.getAttribute("src"))))if(a=this.element.getAttribute("srcdoc")){E(!(" "+this.l+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)var b=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));b=new Uint8Array(a.length);for(var c=0;c<a.length;c++){var d=a.charCodeAt(c);
b[c]=d}}a=btoa;c=Array(b.length);for(d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);b=c.join("");a="data:text/html;charset=utf-8;base64,"+a(b)}else a=void 0;this.iframeSrc=Qa(this,a,this.l)};l.preconnectCallback=function(a){this.iframeSrc&&T(this.win,"preconnect").url(this.getAmpDoc(),this.iframeSrc,a)};
l.buildCallback=function(){this.G=this.getPlaceholder();this.D=!!this.G;(this.F=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");var a=this.element;if("no"!=a.getAttribute("scrolling")){var b=a.ownerDocument.createElement("i-amphtml-scroll-container");a.appendChild(b);a=b}this.A=a;Ta(this)};
l.onLayoutMeasure=function(){Ua(this);var a=this.element;a:{var b=a.getLayoutBox();var c=b.height;b=b.width;for(var d=0;d<N.length;d++){var e=N[d][0],f=N[d][1];if(!(f>c||e>b)&&20>=c-f&&20>=b-e){c=!0;break a}}c=!1}this.L=c;c=this.element;b=c.getLayoutBox();this.o=10<b.width||10<b.height?!1:!la(c);if(c=this.L){c=this.win;b=!1;d=0;do Ma[a.tagName]?(d++,b=!1):(e=(c.getComputedStyle(a)||Object.create(null)).position,"fixed"!=e&&"sticky"!=e||(b=!0)),a=a.parentElement;while(a&&"BODY"!=a.tagName);c=!(!b&&
1>=d)}this.R=c};function Ua(a){if(a.h){var b=a.getViewport().getLayoutRect(a.h),c=a.getLayoutBox();a.J=Ba(b,-c.left,-c.top)}}l.getIntersectionElementLayoutBox=function(){if(!this.h)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.J||Ua(this);return Ba(this.J,a.left,a.top)};
l.layoutCallback=function(){var a=this;E(!this.R,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.D||Ra(this);this.F&&E(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return v();if(this.o&&!this.getAmpDoc().registerSingleton(1))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
v();var b=this.element.ownerDocument.createElement("iframe");this.h=b;this.applyFillContent(b);b.name="amp_iframe"+Oa++;this.D&&ua(b,-1);this.propagateAttributes(Na,b);var c=b.getAttribute("allow")||"";c=c.replace("autoplay","autoplay-disabled");b.setAttribute("allow",c);b.setAttribute("sandbox",this.l||"");b.src=this.iframeSrc;this.o||(this.B=new Da(this,b));b.onload=function(){b.readyState="complete";a.O();a.o&&(a.iframeSrc=null,T(a.win,"timer").promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);
a.element.setAttribute("amp-removed","");a.h=null}))};L(b,"embed-size",function(b){Z(a,b.height,b.width)},void 0,void 0,!0);this.H=pa(this.win,function(b){if(a.h&&b.source===a.h.contentWindow&&(b=b.data,"string"===typeof b&&H(b,"pym"))){var c=b.split(/xPYMx/);"height"===c[2]?Z(a,parseInt(c[3],10),void 0):"width"===c[2]?Z(a,void 0,parseInt(c[3],10)):C().warn("amp-iframe","Unsupported Pym.js message: "+b)}});this.D&&L(b,"embed-ready",this.O.bind(this));L(b,"send-consent-data",function(b,c,f){Va(a,c,
f)});this.A.appendChild(b);return this.loadPromise(b).then(function(){a.A!=a.element&&T(a.win,"timer").delay(function(){a.mutateElement(function(){a.A.classList.add("amp-active")})},1E3)})};function Va(a,b,c){var d=AMP.BaseElement.prototype.getConsentPolicy.call(a)||"default",e=Wa(a,d),f=Xa(a,d),g=Ya(a,d);Promise.all([f,e,g]).then(function(a){var d=F({sentinel:"amp",type:"consent-data",consentMetadata:a[0],consentString:a[1],consentPolicyState:a[2]});b.postMessage(d,c)})}
function Wa(a,b){return Ka(a.element,void 0===b?"default":b)}function Xa(a,b){return La(a.element,void 0===b?"default":b)}function Ya(a,b){return Ja(a.element,void 0===b?"default":b)}l.unlayoutOnPause=function(){return!0};l.unlayoutCallback=function(){this.H&&(this.H(),this.H=null);if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.G&&this.togglePlaceholder(!0);this.h=null;this.B&&(this.B.destroy(),this.B=null)}return!0};
l.getLayoutPriority=function(){return this.L?2:this.o?1:AMP.BaseElement.prototype.getLayoutPriority.call(this)};l.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=Sa(this,b),this.h&&(this.h.src=Qa(this,this.iframeSrc,this.l)));this.h&&a.title&&this.propagateAttributes(["title"],this.h)};l.O=function(){var a=this;this.G&&this.getVsync().mutate(function(){a.h&&(ua(a.h,0),a.togglePlaceholder(!1))})};l.firstLayoutCompleted=function(){};
l.throwIfCannotNavigate=function(){if(!/\sallow-top-navigation\s/i.test(" "+this.l+" "))throw C().createError('"AMP.navigateTo" is only allowed on <amp-iframe> when its "sandbox" attribute contains "allow-top-navigation".');};
function Z(a,b,c){if(a.F)if(100>b)a.user().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var d,e;b=parseInt(b,10);isNaN(b)||(d=Math.max(b+(a.element.offsetHeight-a.h.offsetHeight),b));c=parseInt(c,10);isNaN(c)||(e=Math.max(c+(a.element.offsetWidth-a.h.offsetWidth),c));void 0!==d||void 0!==e?a.attemptChangeSize(d,e).then(function(){void 0!==d&&a.element.setAttribute("height",
d);void 0!==e&&a.element.setAttribute("width",e);a.element.overflowCallback(!1,d,e)},function(){}):a.user().error("amp-iframe","Ignoring embed-size request because no width or height value is provided",a.element)}else a.P||(a.user().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element),a.P=!0)}
function Ta(a){if(Fa(a.win,"iframe-messaging")){var b=a.element,c=b.getAttribute("src");c&&(a.j=O(b,"url").parse(c).origin);a.registerAction("postMessage",function(b){a.j?a.h.contentWindow.postMessage(b.args,a.j):C().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')});if(a.j){var d=0,e=function(b){if(b.source===a.h.contentWindow)if(b.origin!==a.j)C().error("amp-iframe",'"message" received from unexpected origin: '+b.origin+". Only allowed from: "+a.j);
else{if(a.getAmpDoc().getRootNode().activeElement!==a.h)var c=!1;else c=a.win.document.createElement("audio"),c.play(),c=c.paused?!1:!0;if(c){var f=b.data;try{var n=JSON.parse(JSON.stringify(f))}catch(t){C().error("amp-iframe",'Data from "message" event must be JSON.');return}var h=a.win;b=F({data:n});c={detail:b};Object.assign(c,void 0);"function"==typeof h.CustomEvent?b=new h.CustomEvent("amp-iframe:message",c):(h=h.document.createEvent("CustomEvent"),h.initCustomEvent("amp-iframe:message",!!c.bubbles,
!!c.cancelable,b),b=h);O(a.element,"action").trigger(a.element,"message",b,3)}else d++,C().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),10<=d&&(C().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),a.win.removeEventListener("message",e))}};a.win.addEventListener("message",e)}}}l.V=function(a){this.j=a};(function(a){a.registerElement("amp-iframe",W)})(self.AMP);
})});

//# sourceMappingURL=MisterOperator-iframe-0.1.js.map
