(self.AMP=self.AMP||[]).push({n:"amp-mustache",v:"2009252320001",f:(function(AMP,_){
'use strict';var m;function aa(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}aa(this);"function"===typeof Symbol&&Symbol("x");var fa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=ha;function ma(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var qa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var w=self.AMP_CONFIG||{},ra=("string"==typeof w.cdnProxyRegex?new RegExp(w.cdnProxyRegex):w.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function sa(a){if(!self.document||!self.document.head||self.location&&ra.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ta={thirdParty:w.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:w.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof w.thirdPartyFrameRegex?new RegExp(w.thirdPartyFrameRegex):w.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:w.cdnUrl||sa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ra,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:w.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:w.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:w.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:w.geoApiUrl||sa("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var ua=self.__AMP_LOG;function A(){if(!ua.user)throw Error("failed to call initLogConstructor");return ua.user}function D(a,b,c){A().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function H(a){return a||{}};function va(){this.G=100;this.o=this.A=0;this.l=Object.create(null)}va.prototype.has=function(a){return!!this.l[a]};va.prototype.get=function(a){var b=this.l[a];if(b)return b.access=++this.o,b.payload};
va.prototype.put=function(a,b){this.has(a)||this.A++;this.l[a]={payload:b,access:this.o};if(!(this.A<=this.G)){if(ua.dev)a=ua.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.l;var c=this.o+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.A--)}};function K(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var wa=H({c:!0,v:!0,a:!0,ad:!0}),xa,ya,za=/[?&]amp_js[^&]*/,Aa=/[?&]amp_gsa[^&]*/,Ba=/[?&]amp_r[^&]*/,Ca=/[?&]amp_kit[^&]*/,Da=/[?&]usqp[^&]*/;
function L(a){xa||(xa=self.document.createElement("a"),ya=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new va));var b=ya,c=xa;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function Pa(a){"string"==typeof a&&(a=L(a));return ta.cdnProxyRegex.test(a.origin)}
function Qa(a){"string"==typeof a&&(a=L(a));if(!Pa(a))return a.href;var b=a.pathname.split("/");D(wa[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);D(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(za,"").replace(Aa,"").replace(Ba,"").replace(Ca,"").replace(Da,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Ra(a,b){"string"==typeof b&&(b=L(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=L(d));c=c.replace(/\\/g,"/");var e=L(c);c=K(c.toLowerCase(),e.protocol)?e.href:K(c,"//")?d.protocol+c:K(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}
function Sa(a){var b=L(a).search,c=Object.create(null);if(b)for(var d;d=qa.exec(b);){var e=ma(d[1],d[1]);d=d[2]?ma(d[2].replace(/\+/g," "),d[2]):"";c[e]=d}D(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Ta(a,b){var c=a=a.__AMP_TOP||(a.__AMP_TOP=a),d=Ua(c),e=d.purifier;e||(e=d.purifier={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=b,e.context=a,e.resolve&&Va(c,"purifier"))}function Wa(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Va(a,b)}function Xa(a){return a.nodeType?Wa((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function Va(a,b){a=Ua(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ua(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Ya(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function M(a,b){this.element=a;this.win=a.ownerDocument.defaultView||b;a=Xa(this.element);a=Xa(a);a=a.isSingleDoc()?a.win:a;this.I=Va(a,"viewer");this.compileCallback()}m=M.prototype;m.compileCallback=function(){};m.setHtml=function(){};m.render=function(){};m.renderAsString=function(){};function Za(a,b){for(a=a.firstChild;null!=a;a=a.nextSibling)if(3==a.nodeType){var c=a.textContent.trim();c&&b(c)}else 8!=a.nodeType&&1==a.nodeType&&b(a)}
m.tryUnwrap=function(a){var b;Za(a,function(a){b=void 0===b&&a.nodeType?a:null});return b||a};m.unwrapChildren=function(a){var b=this,c=[];Za(a,function(a){if("string"==typeof a){var d=b.win.document.createElement("div");d.textContent=a;c.push(d)}else c.push(a)});return c};m.viewerCanRenderTemplates=function(){return this.I.hasCapability("viewerRenderTemplate")};function $a(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};var ab=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function bb(a){for(var b=[],c;c=ab.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var q=c[3].toLowerCase();if("w"==q)e=parseInt(c[2],10);else if("x"==q)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new cb(b)}
function cb(a){D(0<a.length,"Srcset must have at least one source");this.j=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}D(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?db:eb);this.F=b}
cb.prototype.select=function(a,b){if(this.F){b*=a;a=this.j;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var q=a[f].width,n=Math.abs(q-b);if(n<=1.1*d||1.2<b/e)c=f,d=n,e=q;else break}b=c}else{a=this.j;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.j[b].url};cb.prototype.getUrls=function(){return this.j.map(function(a){return a.url})};
cb.prototype.stringify=function(a){for(var b=[],c=this.j,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.F?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function db(a,b){D(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function eb(a,b){D(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};function fb(a,b,c){return gb(b)?hb(a,b,c):c}function gb(a){return"src"==a||"href"==a||"xlink:href"==a||"srcset"==a}function hb(a,b,c){var d=self.location;Sa(c);var e=Pa(d),f=L(Qa(d));if("href"==b&&!K(c,"#"))return Ra(c,f);if("src"==b)return"amp-img"==a?ib(c,f,e):Ra(c,f);if("srcset"==b){try{var q=bb(c)}catch(n){return A().error("URL-REWRITE","Failed to parse srcset: ",n),c}return q.stringify(function(a){return ib(a,f,e)})}return c}
function ib(a,b,c){a=L(Ra(a,b));return"data:"==a.protocol||Pa(a)||!c?a.href:ta.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var jb={"AMP-IMG":["src","srcset","layout","width","height"]};function kb(a,b){var c=K(a.tagName,"AMP-"),d=a.hasAttribute("i-amphtml-binding");if(!d&&jb[a.tagName])a.setAttribute("i-amphtml-ignore","");else if(d||c)a.hasAttribute("i-amphtml-key")||a.setAttribute("i-amphtml-key",b())}
var lb={applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,style:!0,video:!0},mb={"amp-accordion":!0,"amp-anim":!0,"amp-bind-macro":!0,"amp-carousel":!0,"amp-fit-text":!0,"amp-img":!0,"amp-layout":!0,"amp-selector":!0,"amp-sidebar":!0,"amp-timeago":!0},nb="a b br caption code col colgroup dd del div dl dt em hr i ins li mark ol p q s small span strong sub sup table tbody td tfoot th thead time tr u ul".split(" "),ob="amp-fx fallback heights layout min-font-size max-font-size on option placeholder submitting submit-success submit-error validation-for verify-error visible-when-invalid href style text subscriptions-action subscriptions-actions subscriptions-decorate subscriptions-dialog subscriptions-display subscriptions-section subscriptions-service subscriptions-google-rtc amp-nested-submenu amp-nested-submenu-open amp-nested-submenu-close itemprop".split(" "),
pb={a:["rel","target"],div:["template"],form:["action-xhr","verify-xhr","custom-validation-reporting","target"],input:["mask-output"],template:["type"],textarea:["autoexpand"]},qb=["_top","_blank"],rb=/^(?:\w+script|data|blob):/i,sb=/^(?:blob):/i,Cb=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,Db=Object.freeze(H({input:{type:/(?:image|button)/i}})),Eb=Object.freeze(H({input:{type:/(?:button|file|image|password)/i}})),Fb=Object.freeze("form formaction formmethod formtarget formnovalidate formenctype".split(" ")),
Gb=Object.freeze(H({input:Fb,textarea:Fb,select:Fb})),Hb=Object.freeze(H({"amp-anim":["controls"],form:["name"]})),Ib=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function Jb(a,b,c,d){var e=!0,f=e=void 0===e?!1:e,q=c?c.replace(Cb,""):"";if(!f){if(K(b,"on")&&"on"!=b)return!1;var n=q.toLowerCase();if(0<=n.indexOf("<script")||0<=n.indexOf("\x3c/script")||rb.test(q))return!1}if(sb.test(q))return!1;if("style"==b)return!Ib.test(c);if("class"==b&&c&&/(^|\W)i-amphtml-/i.test(c)||gb(b)&&/__amp_source_origin/.test(c))return!1;var v=$a(d),E=Object.assign(Object.create(null),Gb,v?Hb:{})[a];if(E&&-1!=E.indexOf(b))return!1;var B=Object.assign(Object.create(null),Db,v?Eb:
{})[a];if(B){var g=B[b];if(g&&-1!=c.search(g))return!1}return!0};var O=Object.freeze||function(a){return a},Kb=O("a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" ")),
Lb=O("svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" ")),Mb=O("feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" ")),
Nb=O("math menclose merror mfenced mfrac mglyph mi mlabeledtr mmultiscripts mn mo mover mpadded mphantom mroot mrow ms mspace msqrt mstyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" ")),Ob=O(["#text"]),Pb=Object.freeze||function(a){return a},Qb=Pb("accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan controls coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min minlength multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" ")),
Rb=Pb("accent-height accumulate additive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter filterunits flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio primitiveunits r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility version vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" ")),
Sb=Pb("accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle encoding fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" ")),
Tb=Pb(["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"]),Ub=Object.hasOwnProperty,Vb=Object.setPrototypeOf,Wb=("undefined"!==typeof Reflect&&Reflect).apply;Wb||(Wb=function(a,b,c){return a.apply(b,c)});function P(a,b){Vb&&Vb(a,null);for(var c=b.length;c--;){var d=b[c];if("string"===typeof d){var e=d.toLowerCase();e!==d&&(Object.isFrozen(b)||(b[c]=e),d=e)}a[d]=!0}return a}function Xb(a){var b={},c=void 0;for(c in a)Wb(Ub,a,[c])&&(b[c]=a[c]);return b}
var X=Object.seal||function(a){return a},Yb=X(/\{\{[\s\S]*|[\s\S]*\}\}/gm),Zb=X(/<%[\s\S]*|[\s\S]*%>/gm),$b=X(/^data-[\-\w.\u00B7-\uFFFF]/),ac=X(/^aria-[\-\w]+$/),bc=X(/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i),cc=X(/^(?:\w+script|data):/i),dc=X(/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g),ec="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===
Symbol&&a!==Symbol.prototype?"symbol":typeof a};function Y(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}var fc=("undefined"!==typeof Reflect&&Reflect).apply,gc=Array.prototype.slice,hc=Object.freeze;fc||(fc=function(a,b,c){return a.apply(b,c)});
function ic(a,b){if("object"!==("undefined"===typeof a?"undefined":ec(a))||"function"!==typeof a.createPolicy)return null;var c=null;b.currentScript&&b.currentScript.hasAttribute("data-tt-policy-suffix")&&(c=b.currentScript.getAttribute("data-tt-policy-suffix"));var d="dompurify"+(c?"#"+c:"");try{return a.createPolicy(d,{createHTML:function(a){return a}})}catch(e){return console.warn("TrustedTypes policy "+d+" could not be created."),null}}
function jc(){function a(a){var c,na=void 0,k;d("beforeSanitizeAttributes",a,null);var e=a.attributes;if(e){var u={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:r};for(k=e.length;k--;){var p=c=e[k],G=p.name,h=p.namespaceURI;c=c.value.trim();var f=G.toLowerCase();u.attrName=f;u.attrValue=c;u.keepAttr=!0;d("uponSanitizeAttribute",a,u);c=u.attrValue;if("name"===f&&"IMG"===a.nodeName&&e.id)na=e.id,e=fc(gc,e,[]),v("id",a),v(G,a),e.indexOf(na)>k&&a.setAttribute("id",na.value);else if("INPUT"!==
a.nodeName||"type"!==f||"file"!==c||!u.keepAttr||!r[f]&&Ea[f])"id"===G&&a.setAttribute(G,""),v(G,a);else continue;if(u.keepAttr)if(/svg|math/i.test(a.namespaceURI)&&(new RegExp("</("+Object.keys(ub).join("|")+")","i")).test(c))v(G,a);else{S&&(c=c.replace(Yb," "),c=c.replace(Zb," "));var z=a.nodeName.toLowerCase();if(b(z,f,c))try{h?a.setAttributeNS(h,G,c):a.setAttribute(G,c),g.removed.pop()}catch(Hc){}}}d("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(vb&&("id"===b||"name"===b)&&(c in x||
c in vc))return!1;if(!Fa||!$b.test(b))if(!wb||!ac.test(b))if(!r[b]||Ea[b]||!(Ga[b]||t.test(c.replace(dc,""))||("src"===b||"xlink:href"===b||"href"===b)&&"script"!==a&&0===c.indexOf("data:")&&wc[a]||xb&&!cc.test(c.replace(dc,"")))&&c)return!1;return!0}function c(a){d("beforeSanitizeElements",a,null);if(f(a))return E(a),!0;var b=a.nodeName.toLowerCase();d("uponSanitizeElement",a,{tagName:b,allowedTags:l});if(("svg"===b||"math"===b)&&0!==a.querySelectorAll("p, br").length)return E(a),!0;if(!l[b]||F[b]){if(Ha&&
!ub[b]&&"function"===typeof a.insertAdjacentHTML)try{var c=a.innerHTML;a.insertAdjacentHTML("AfterEnd",u?u.createHTML(c):c)}catch(Fc){}E(a);return!0}if("noscript"===b&&/<\/noscript/i.test(a.innerHTML)||"noembed"===b&&/<\/noembed/i.test(a.innerHTML))return E(a),!0;!yb||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(g.removed.push({element:a.cloneNode()}),a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));S&&3===a.nodeType&&
(b=a.textContent,b=b.replace(Yb," "),b=b.replace(Zb," "),a.textContent!==b&&(g.removed.push({element:a.cloneNode()}),a.textContent=b));d("afterSanitizeElements",a,null);return!1}function d(a,b,c){y[a]&&y[a].forEach(function(a){a.call(g,b,c,T)})}function e(a){return"object"===("undefined"===typeof U?"undefined":ec(U))?a instanceof U:a&&"object"===("undefined"===typeof a?"undefined":ec(a))&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof Ia||a instanceof
ba?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof Ja&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute&&"string"===typeof a.namespaceURI?!1:!0}function q(a){return xc.call(a.ownerDocument||a,a,V.SHOW_ELEMENT|V.SHOW_COMMENT|V.SHOW_TEXT,function(){return V.FILTER_ACCEPT},!1)}function n(a){var b=void 0,c=void 0;if(Ka)a="<remove></remove>"+a;else{var d=a.match(/^[\s]+/);(c=d&&d[0])&&(a=a.slice(c.length))}if(Q)try{b=
(new k).parseFromString(a,"text/html")}catch(Gc){}I&&P(F,["title"]);b&&b.documentElement||(b=La.createHTMLDocument(""),d=b.body,d.parentNode.removeChild(d.parentNode.firstElementChild),d.outerHTML=u?u.createHTML(a):a);a&&c&&b.body.insertBefore(x.createTextNode(c),b.body.childNodes[0]||null);return N.call(b,ca?"html":"body")[0]}function v(a,b){try{g.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(tb){g.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function E(a){g.removed.push({element:a});
try{a.parentNode.removeChild(a)}catch(uc){a.outerHTML=G}}function B(a){T&&T===a||(a&&"object"===("undefined"===typeof a?"undefined":ec(a))||(a={}),l="ALLOWED_TAGS"in a?P({},a.ALLOWED_TAGS):C,r="ALLOWED_ATTR"in a?P({},a.ALLOWED_ATTR):zb,Ga="ADD_URI_SAFE_ATTR"in a?P(Xb(Ab),a.ADD_URI_SAFE_ATTR):Ab,F="FORBID_TAGS"in a?P({},a.FORBID_TAGS):{},Ea="FORBID_ATTR"in a?P({},a.FORBID_ATTR):{},W="USE_PROFILES"in a?a.USE_PROFILES:!1,wb=!1!==a.ALLOW_ARIA_ATTR,Fa=!1!==a.ALLOW_DATA_ATTR,xb=a.ALLOW_UNKNOWN_PROTOCOLS||
!1,yb=a.SAFE_FOR_JQUERY||!1,S=a.SAFE_FOR_TEMPLATES||!1,ca=a.WHOLE_DOCUMENT||!1,da=a.RETURN_DOM||!1,Ma=a.RETURN_DOM_FRAGMENT||!1,Bb=a.RETURN_DOM_IMPORT||!1,Na=a.RETURN_TRUSTED_TYPE||!1,Ka=a.FORCE_BODY||!1,vb=!1!==a.SANITIZE_DOM,Ha=!1!==a.KEEP_CONTENT,oa=a.IN_PLACE||!1,t=a.ALLOWED_URI_REGEXP||t,S&&(Fa=!1),Ma&&(da=!0),W&&(l=P({},[].concat(Y(Ob))),r=[],!0===W.html&&(P(l,Kb),P(r,Qb)),!0===W.svg&&(P(l,Lb),P(r,Rb),P(r,Tb)),!0===W.svgFilters&&(P(l,Mb),P(r,Rb),P(r,Tb)),!0===W.mathMl&&(P(l,Nb),P(r,Sb),P(r,
Tb))),a.ADD_TAGS&&(l===C&&(l=Xb(l)),P(l,a.ADD_TAGS)),a.ADD_ATTR&&(r===zb&&(r=Xb(r)),P(r,a.ADD_ATTR)),a.ADD_URI_SAFE_ATTR&&P(Ga,a.ADD_URI_SAFE_ATTR),Ha&&(l["#text"]=!0),ca&&P(l,["html","head","body"]),l.table&&(P(l,["tbody"]),delete F.tbody),hc&&hc(a),T=a)}function g(a){return jc(a)}var h=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;g.version="2.0.7";g.removed=[];if(!h||!h.document||9!==h.document.nodeType)return g.isSupported=!1,g;var ea=h.document,
Q=!1,I=!1,x=h.document,pa=h.DocumentFragment,U=h.Node,V=h.NodeFilter,J=h.NamedNodeMap,Ja=void 0===J?h.NamedNodeMap||h.MozNamedAttrMap:J,Ia=h.Text,ba=h.Comment,k=h.DOMParser,p=h.TrustedTypes;"function"===typeof h.HTMLTemplateElement&&(J=x.createElement("template"),J.content&&J.content.ownerDocument&&(x=J.content.ownerDocument));var u=ic(p,ea),G=u?u.createHTML(""):"",z=x,La=z.implementation,xc=z.createNodeIterator,N=z.getElementsByTagName,yc=z.createDocumentFragment,R=ea.importNode,y={};g.isSupported=
La&&"undefined"!==typeof La.createHTMLDocument&&9!==x.documentMode;var t=bc,l=null,C=P({},[].concat(Y(Kb),Y(Lb),Y(Mb),Y(Nb),Y(Ob))),r=null,zb=P({},[].concat(Y(Qb),Y(Rb),Y(Sb),Y(Tb))),F=null,Ea=null,wb=!0,Fa=!0,xb=!1,yb=!1,S=!1,ca=!1,Oa=!1,Ka=!1,da=!1,Ma=!1,Bb=!1,Na=!1,vb=!0,Ha=!0,oa=!1,W={},ub=P({},"annotation-xml audio colgroup desc foreignobject head iframe math mi mn mo ms mtext noembed noframes plaintext script style svg template thead title video xmp".split(" ")),wc=P({},["audio","video","img",
"source","image"]),Ga=null,Ab=P({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),T=null,vc=x.createElement("form");g.isSupported&&(function(){try{n('<svg><p><textarea><img src="</textarea><img src=x abc=1//">').querySelector("svg img")&&(Q=!0)}catch(na){}}(),function(){try{var a=n("<x/><title>&lt;/title&gt;&lt;img&gt;");/<\/title/.test(a.querySelector("title").innerHTML)&&(I=!0)}catch(uc){}}());var zc=function tb(b){var k=void 0,e=q(b);for(d("beforeSanitizeShadowDOM",
b,null);k=e.nextNode();)d("uponSanitizeShadowNode",k,null),c(k)||(k.content instanceof pa&&tb(k.content),a(k));d("afterSanitizeShadowDOM",b,null)};g.sanitize=function(b,d){var k=void 0,p=void 0,f=void 0,z=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!e(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");}if(!g.isSupported){if("object"===ec(h.toStaticHTML)||"function"===
typeof h.toStaticHTML){if("string"===typeof b)return h.toStaticHTML(b);if(e(b))return h.toStaticHTML(b.outerHTML)}return b}Oa||B(d);g.removed=[];if(!oa)if(b instanceof U)k=n("\x3c!--\x3e"),p=k.ownerDocument.importNode(b,!0),1===p.nodeType&&"BODY"===p.nodeName?k=p:"HTML"===p.nodeName?k=p:k.appendChild(p);else{if(!da&&!S&&!ca&&Na&&-1===b.indexOf("<"))return u?u.createHTML(b):b;k=n(b);if(!k)return da?null:G}k&&Ka&&E(k.firstChild);for(var l=q(oa?b:k);d=l.nextNode();)3===d.nodeType&&d===f||c(d)||(d.content instanceof
pa&&zc(d.content),a(d),f=d);f=null;if(oa)return b;if(da){if(Ma)for(z=yc.call(k.ownerDocument);k.firstChild;)z.appendChild(k.firstChild);else z=k;Bb&&(z=R.call(ea,z,!0));return z}var N=ca?k.outerHTML:k.innerHTML;S&&(N=N.replace(Yb," "),N=N.replace(Zb," "));return u&&Na?u.createHTML(N):N};g.setConfig=function(a){B(a);Oa=!0};g.clearConfig=function(){T=null;Oa=!1};g.isValidAttribute=function(a,c,d){T||B({});a=a.toLowerCase();c=c.toLowerCase();return b(a,c,d)};g.addHook=function(a,b){"function"===typeof b&&
(y[a]=y[a]||[],y[a].push(b))};g.removeHook=function(a){y[a]&&y[a].pop()};g.removeHooks=function(a){y[a]&&(y[a]=[])};g.removeAllHooks=function(){y={}};return g}var kc=jc();var lc={script:{attribute:"type",values:["application/json","application/ld+json"]}},mc={USE_PROFILES:{html:!0,svg:!0,svgFilters:!0}};function nc(a){this.m=a;this.H=1;this.h=kc(self);this.B=kc(self);a=Object.assign({},Object.assign({},mc,{ADD_ATTR:ob,ADD_TAGS:["use"],FORBID_TAGS:Object.keys(lb),FORCE_BODY:!0,RETURN_DOM:!0,ALLOW_UNKNOWN_PROTOCOLS:!0}));this.h.setConfig(a);oc(this,this.h);pc(this.B)}nc.prototype.purifyHtml=function(a){return this.h.sanitize(a)};
nc.prototype.purifyTagsForTripleMustache=function(a){a=this.B.sanitize(a,{ALLOWED_TAGS:nb,FORCE_BODY:!0,RETURN_DOM_FRAGMENT:!0});var b=this.m.createElement("div");b.appendChild(a);return b.innerHTML};nc.prototype.getAllowedTags=function(){var a={};this.h.addHook("uponSanitizeElement",function(b,d){Object.assign(a,d.allowedTags)});var b=this.m.createElement("p");this.h.sanitize(b);Object.keys(lb).forEach(function(b){a[b]=!1});this.h.removeHook("uponSanitizeElement");return a};
nc.prototype.validateAttributeChange=function(a,b,c){var d=a.nodeName.toLowerCase(),e=lc[d];if(e){var f=e.values;if(e.attribute===b&&(null==c||!f.includes(c)))return!1}if("a"===d&&"target"===b&&(null==c||!qb.includes(c)))return!1;if(null==c)return!0;if(qc(b)!==rc)return!1;if(!this.h.isValidAttribute(d,b,c)){var q=pb[d];if(!(q&&q.includes(b)||K(d,"amp-")))return!1}a=a.ownerDocument?a.ownerDocument:a;return c&&!Jb(d,b,c,a)?!1:!0};
function oc(a,b){var c=$a(a.m),d,e=[],f,q=[];b.addHook("uponSanitizeElement",function(a,b){var f=b.tagName;d=b.allowedTags;K(f,"amp-")&&(d[f]=!c||mb[f]);"a"===f&&a.hasAttribute("href")&&!a.hasAttribute("target")&&a.setAttribute("target","_top");var n=lc[f];n&&(b=n.attribute,n=n.values,a.hasAttribute(b)&&n.includes(a.getAttribute(b))&&(d[f]=!0,e.push(f)))});b.addHook("afterSanitizeElements",function(){e.forEach(function(a){delete d[a]});e.length=0});b.addHook("uponSanitizeAttribute",function(b,c){function d(){f[g]||
(f[g]=!0,q.push(g))}var e=b.nodeName.toLowerCase(),g=c.attrName,h=c.attrValue;f=c.allowedAttributes;if(K(e,"amp-"))d();else{if("a"==e&&"target"==g){var n=h.toLowerCase();h=qb.includes(n)?n:"_top"}var v=pb[e];v&&v.includes(g)&&d()}var I=qc(g);I===sc&&(v=g.substring(1,g.length-1),b.setAttribute("data-amp-bind-"+v,h));I!==rc&&b.setAttribute("i-amphtml-binding","");Jb(e,g,h,a.m)?fb&&h&&!K(g,"data-amp-bind-")&&(h=fb(e,g,h)):(c.keepAttr=!1,A().error("purifier",'Removed invalid attribute %s[%s="%s"].',e,
g,h));c.attrValue=h});b.addHook("afterSanitizeAttributes",function(b){kb(b,function(){return String(a.H++)});q.forEach(function(a){delete f[a]});q.length=0;"use"===b.nodeName.toLowerCase()&&["href","xlink:href"].forEach(function(a){b.hasAttribute(a)&&!K(b.getAttribute(a),"#")&&(b.parentElement&&b.parentElement.removeChild(b),A().error("purifier",'Removed invalid <use>. use[href] must start with "#".'))})})}
function pc(a){var b;a.addHook("uponSanitizeElement",function(a,d){var c=d.tagName;b=d.allowedTags;"template"===c&&(a=a.getAttribute("type"))&&"amp-mustache"===a.toLowerCase()&&(b.template=!0)});a.addHook("afterSanitizeElements",function(){b.template=!1})}var rc=0,sc=1,tc=2;function qc(a){return"["==a[0]&&"]"==a[a.length-1]?sc:K(a,"data-amp-bind-")?tc:rc};/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
var Ac={};
(function(a){function b(a){return"function"===typeof a}function c(a){return Q(a)?"array":typeof a}function d(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function e(a,b){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,b)}function f(a,b){return I.call(a,b)}function q(a){return!f(x,a)}function n(b,c){function k(){if(g&&!h)for(;f.length;)delete p[f.pop()];else f=[];h=g=!1}if(!b)return[];var e=[],p=[],f=[],g=!1,h=!1,n,R,y;(function(a){"string"===typeof a&&(a=a.split(V,
2));if(!Q(a)||2!==a.length)throw Error("Invalid tags: "+a);n=new RegExp(d(a[0])+"\\s*");R=new RegExp("\\s*"+d(a[1]));y=new RegExp("\\s*"+d("}"+a[1]))})(c||a.tags);for(var t=new B(b),l,C,r,x,F;!t.eos();){b=t.pos;if(C=t.scanUntil(n)){l=0;for(var I=C.length;l<I;++l)r=C.charAt(l),q(r)?f.push(p.length):h=!0,p.push(["text",r,b,b+1]),b+=1,"\n"===r&&k()}if(!t.scan(n))break;g=!0;l=t.scan(Ia)||"name";t.scan(U);"="===l?(C=t.scanUntil(J),t.scan(J),t.scanUntil(R)):"{"===l?(C=t.scanUntil(y),t.scan(Ja),t.scanUntil(R),
l="&"):C=t.scanUntil(R);if(!t.scan(R))throw Error("Unclosed tag at "+t.pos);x=[l,C,b,t.pos];p.push(x);if("#"===l||"^"===l)e.push(x);else if("/"===l){F=e.pop();if(!F)throw Error('Unopened section "'+C+'" at '+b);if(F[1]!==C)throw Error('Unclosed section "'+F[1]+'" at '+b);}else if("name"===l||"{"===l||"&"===l)h=!0}if(F=e.pop())throw Error('Unclosed section "'+F[1]+'" at '+t.pos);return E(v(p))}function v(a){for(var b=[],c,d,k=0,e=a.length;k<e;++k)if(c=a[k])"text"===c[0]&&d&&"text"===d[0]?(d[1]+=c[1],
d[3]=c[3]):(b.push(c),d=c);return b}function E(a){for(var b=[],c=b,d=[],k,e,f=0,g=a.length;f<g;++f)switch(k=a[f],k[0]){case "#":case "^":c.push(k);d.push(k);c=k[4]=[];break;case "/":e=d.pop();e[5]=k[2];c=0<d.length?d[d.length-1][4]:b;break;default:c.push(k)}return b}function B(a){this.tail=this.string=a;this.pos=0}function g(a,b){this.view=a;this.cache={".":this.view};this.parent=b}function h(){this.cache={}}var ea=Object.prototype.toString,Q=Array.isArray||function(a){return"[object Array]"===ea.call(a)},
I=RegExp.prototype.test,x=/\S/,pa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},U=/\s*/,V=/\s+/,J=/\s*=/,Ja=/\s*\}/,Ia=/#|\^|\/|>|\{|&|=|!/;B.prototype.eos=function(){return""===this.tail};B.prototype.scan=function(a){a=this.tail.match(a);if(!a||0!==a.index)return"";a=a[0];this.tail=this.tail.substring(a.length);this.pos+=a.length;return a};B.prototype.scanUntil=function(a){a=this.tail.search(a);switch(a){case -1:var b=this.tail;this.tail="";break;
case 0:b="";break;default:b=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=b.length;return b};g.prototype.push=function(a){return new g(a,this)};g.prototype.lookup=function(a){var c=this.cache;if(c.hasOwnProperty(a))var d=c[a];else{for(var k=this,f,g,h=!1;k;){if(0<a.indexOf("."))for(d=k.view,f=a.split("."),g=0;null!=d&&g<f.length;){if(!e(d,f[g])){d=null;break}g===f.length-1&&(h=!0);d=d[f[g++]]}else e(k.view,a)?(d=k.view[a],h=!0):d=null;if(h)break;k=k.parent}c[a]=d}b(d)&&(d=d.call(this.view));
return d};h.prototype.clearCache=function(){this.cache={}};h.prototype.parse=function(a,b){var c=this.cache,d=c[a];null==d&&(d=c[a]=n(a,b));return d};h.prototype.render=function(a,b,c){var d=this.parse(a);b=b instanceof g?b:new g(b);return this.renderTokens(d,b,c,a)};h.prototype.renderTokens=function(a,b,c,d){for(var k="",e,f,g,h=0,p=a.length;h<p;++h)g=void 0,e=a[h],f=e[0],"#"===f?g=this.renderSection(e,b,c,d):"^"===f?g=this.renderInverted(e,b,c,d):">"===f?g=this.renderPartial(e,b,c,d):"&"===f?g=
this.unescapedValue(e,b):"name"===f?g=this.escapedValue(e,b):"text"===f&&(g=this.rawValue(e)),void 0!==g&&(k+=g);return k};h.prototype.renderSection=function(a,c,d,e){function k(a){return f.render(a,c,d)}var f=this,g="",h=c.lookup(a[1]);if(h){if(Q(h))for(var p=0,u=h.length;p<u;++p)g+=this.renderTokens(a[4],c.push(h[p]),d,e);else if("object"===typeof h||"string"===typeof h||"number"===typeof h)g+=this.renderTokens(a[4],c.push(h),d,e);else if(b(h)){if("string"!==typeof e)throw Error("Cannot use higher-order sections without the original template");
h=h.call(c.view,e.slice(a[3],a[5]),k);null!=h&&(g+=h)}else g+=this.renderTokens(a[4],c,d,e);return g}};h.prototype.renderInverted=function(a,b,c,d){var e=b.lookup(a[1]);if(!e||Q(e)&&0===e.length)return this.renderTokens(a[4],b,c,d)};h.prototype.renderPartial=function(a,c,d){if(d&&(a=b(d)?d(a[1]):d[a[1]],null!=a))return this.renderTokens(this.parse(a),c,d,a)};h.prototype.unescapedValue=function(b,c){b=c.lookup(b[1]);if(null!=b)return a.sanitizeUnescaped?a.sanitizeUnescaped(b):b};h.prototype.escapedValue=
function(b,c){b=c.lookup(b[1]);if(null!=b)return a.escape(b)};h.prototype.rawValue=function(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var ba=new h;a.clearCache=function(){return ba.clearCache()};a.parse=function(a,b){return ba.parse(a,b)};a.render=function(a,b,d){if("string"!==typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+c(a)+'" was given as the first argument for mustache#render(template, view, partials)');return ba.render(a,
b,d)};a.to_html=function(c,d,e,f){c=a.render(c,d,e);if(b(f))f(c);else return c};a.escape=function(a){return String(a).replace(/[&<>"'`=\/]/g,function(a){return pa[a]})};a.sanitizeUnescaped=null;a.setUnescapedSanitizer=function(b){a.sanitizeUnescaped=b};a.Scanner=B;a.Context=g;a.Writer=h})(Ac);function Z(a,b){M.call(this,a,b);var c=this;Ta(b,function(){return new nc(b.document)});this.w=Wa(b,"purifier");Ac.setUnescapedSanitizer(function(a){return c.w.purifyTagsForTripleMustache(a)})}Z.prototype=fa(M.prototype);Z.prototype.constructor=Z;if(la)la(Z,M);else for(var Bc in M)if("prototype"!=Bc)if(Object.defineProperties){var Cc=Object.getOwnPropertyDescriptor(M,Bc);Cc&&Object.defineProperty(Z,Bc,Cc)}else Z[Bc]=M[Bc];Z.J=M.prototype;
Z.prototype.compileCallback=function(){if(!this.viewerCanRenderTemplates()){this.C={};if("TEMPLATE"==this.element.tagName){var a=this.element;if("content"in a)var b=a.content.cloneNode(!0);else{b=a.ownerDocument.createDocumentFragment();var c=b.ownerDocument.createDocumentFragment();for(a=a.firstChild;a;a=a.nextSibling)c.appendChild(a.cloneNode(!0));b.appendChild(c)}Dc(this,b);c=this.element.ownerDocument.createElement("div");c.appendChild(b);b=c.innerHTML}else b="SCRIPT"==this.element.tagName?this.element.textContent:
"";this.D=b;try{Ac.parse(this.D,void 0)}catch(d){A().error("amp-mustache",d.message,this.element)}}};function Dc(a,b){var c=b.querySelectorAll("template");Ya(c,function(b,c){c="__AMP_NESTED_TEMPLATE_"+c;a.C[c]=b.outerHTML;var d=a.element.ownerDocument.createTextNode("{{{"+c+"}}}");b.parentNode.replaceChild(d,b)})}Z.prototype.setHtml=function(a){var b=this.tryUnwrap(this.w.purifyHtml("<div><div>"+(a+"</div></div>")).firstElementChild);return this.unwrapChildren(b)};
Z.prototype.render=function(a){return this.tryUnwrap(Ec(this,a))};Z.prototype.renderAsString=function(a){return Ec(this,a).innerHTML};function Ec(a,b){var c=b;"object"===typeof b&&(c=Object.assign({},b,a.C));b=Ac.render(a.D,c,void 0);return a.w.purifyHtml("<div>"+b+"</div>").firstElementChild}(function(a){a.registerTemplate("amp-mustache",Z)})(self.AMP);
})});

//# sourceMappingURL=MisterOperator-mustache-0.2.js.map
